// Planetary Dosha Remedies (Dosha Nivaran) — full reference data (12 doshas).
// Source: curated Vedic Jyotish guide (Brihat Parashara Hora Shastra tradition).
// 9 planetary doshas + 3 compound doshas.

export const RAW_DOSHAS = [
  // ── SUN ──
  {
    id: "surya-dosha", category: "sun", name: "Surya Dosha", sanskrit: "सूर्य दोष",
    icon: "☀️", planetLabel: "Surya — The Sun",
    colors: { art: "linear-gradient(135deg,#2d1500,#4a2500)", accent: "#E8710A", badge: "#FF8C00" },
    severity: { dosha: 65, health: 70, career: 60, relations: 55 },
    shortDesc: "When the Sun is weak, debilitated, or afflicted in the birth chart, creating obstacles in authority, confidence, health, and the relationship with one's father and government.",
    what: "Surya Dosha arises when the Sun — lord of the soul, vitality, authority, and dharma — is placed unfavorably in the Kundali. This includes Sun in Libra (neech/debilitation), Sun in the 6th, 8th, or 12th house, or Sun conjunct with Saturn, Rahu, or Ketu. The Sun governs the third chakra (Manipura) — when afflicted, self-confidence, leadership, and life force are dimmed.",
    why: "According to the BPHS, the Sun rules the Atmakaraka — the soul's purpose in this incarnation. An afflicted Sun indicates karma around authority, ego, and the father figure from past lives. Sun-Saturn conjunction creates Shrapit Dosha; Sun-Rahu creates Grahan Dosha — the solar eclipse pattern in the birth chart.",
    effects: [
      { i: "😔", t: "Low confidence and self-doubt — inability to assert oneself" },
      { i: "❤️‍🩹", t: "Heart problems, eye disorders, weak immunity and vitality" },
      { i: "👨", t: "Troubled relationship with father or father figures; paternal karma" },
      { i: "🏛️", t: "Conflicts with government, authorities, and bosses" },
      { i: "💼", t: "Career setbacks, inability to rise to leadership positions" },
      { i: "🌑", t: "Identity confusion — unclear sense of purpose and direction" },
    ],
    puja: { name: "Surya Namaskara Puja & Aditya Hridayam Path", detail: "Perform daily Surya Namaskar facing the rising sun. Offer arghya (copper vessel of water with red flowers and red sandalwood) to the sun at sunrise. The Aditya Hridayam — the solar hymn from the Ramayana chanted by the sage Agastya before Rama's battle — is the most powerful remedy. Perform Surya Puja at Suryanar Kovil (Tamil Nadu) or Konark Sun Temple." },
    mantra: { san: "ॐ ह्रीं ह्रीं सूर्याय सहस्रकिरणाय मनोवांछित फलं देहि देहि स्वाहा", mean: "Om Hreem Hreem Suryaya Sahasrakiirana — O Sun of a thousand rays, fulfill my heart's deepest desire.", count: "7,000 times total or 108 times daily for 7 Sundays" },
    timing: [
      { l: "Sacred Day", v: "Sunday (Ravivar)" },
      { l: "Best Time", v: "Sunrise — first hour" },
      { l: "Nakshatra", v: "Kritika, Uttara Phalguni, Uttara Ashadha" },
      { l: "Month", v: "Makar Sankranti especially potent" },
      { l: "Direction", v: "Face East while performing" },
      { l: "Color", v: "Wear red or saffron" },
    ],
    gem: { stone: "Ruby (Manik)", alt: "Red Spinel or Red Garnet", metal: "Gold", finger: "Ring finger (right hand)", when: "Sunday sunrise, after priest's consultation" },
    daan: "Donate on Sundays: wheat, jaggery (gur), copper vessel, red cloth, red flowers, red sandalwood to a Brahmin or temple. Feed wheat bread to crows. Respect your father and elders consistently.",
    remedies: [
      { i: "🌊", t: "Arghya (Water Offering)", d: "Offer water to the sun every morning from a copper vessel — say \"Om Suryaya Namah\" while pouring. This one practice alone can transform Surya Dosha over months." },
      { i: "📖", t: "Surya Ashtottaram", d: "Chant the 108 names of Surya on Sundays. Each name invokes a specific solar attribute." },
      { i: "🍊", t: "Fast on Sundays", d: "Take only one meal — no salt. Offer the saved food as donation. This directly propitiates Surya." },
      { i: "🏛️", t: "Konark / Suryanar Temple", d: "Visit a Surya temple and perform special puja. Konark (Odisha) and Suryanar Kovil (Tamil Nadu) are the most powerful." },
    ],
    joy: [
      { i: "☀️", t: "Radiant Confidence", d: "Natural leadership and authority flow without effort" },
      { i: "💪", t: "Vital Health", d: "Heart strength, eyesight, and life force restored" },
      { i: "👨‍👧", t: "Father's Blessings", d: "Relationship with father and authority figures healed" },
      { i: "🌟", t: "Divine Purpose", d: "Soul's true path becomes brilliantly clear" },
    ],
  },
  // ── MOON ──
  {
    id: "chandra-dosha", category: "moon", name: "Chandra Dosha", sanskrit: "चन्द्र दोष",
    icon: "🌙", planetLabel: "Chandra — The Moon",
    colors: { art: "linear-gradient(135deg,#0a0a40,#15155e)", accent: "#5b6bd6", badge: "#8888FF" },
    severity: { dosha: 70, health: 65, career: 50, relations: 75 },
    shortDesc: "The Moon afflicted in the birth chart — causing emotional turbulence, mental anxiety, depression, relationship difficulties, and disturbed sleep.",
    what: "Chandra Dosha arises when the Moon is placed in the 6th, 8th, or 12th house; in debilitation (Scorpio/Vrischika); conjunct malefics (Saturn, Rahu, Ketu, Mars); or unsupported by benefics. Kemadruma Yoga — when no planet flanks the Moon in adjacent houses — is especially debilitating. The Moon governs mind (manas), emotions, mother, and the subconscious.",
    why: "The Moon represents the mind itself in Jyotish. Chandra Dosha indicates past-life karma around emotional wounds, separation from the mother, or emotional manipulation. In the Yogasutra tradition, an afflicted Chandra creates \"chitta vikshepa\" — the scattered, restless mind unable to find rest.",
    effects: [
      { i: "😰", t: "Chronic anxiety, depression, and emotional instability" },
      { i: "😴", t: "Insomnia, nightmares, disturbed sleep patterns" },
      { i: "👩", t: "Troubled relationship with mother; maternal karma" },
      { i: "💧", t: "Excessive moodiness, uncontrolled emotions, tearfulness" },
      { i: "🧠", t: "Mental disorders — in severe cases, psychosis or fragmentation" },
      { i: "💑", t: "Relationship difficulties — trust issues, emotional unavailability" },
    ],
    puja: { name: "Chandra Puja & Chandra Shanti Homam", detail: "Perform Chandra Puja on Mondays and on Purnima (full moon nights). Offer white items — milk, white rice, white flowers — to a Shiva Linga (Shiva wears the Moon as an ornament). The Shiva Manasa Puja — mental worship offered silently — is especially powerful for Chandra Dosha as it works on the subtle mental level." },
    mantra: { san: "ॐ सों सोमाय नमः | ॐ श्रां श्रीं श्रौं सः चन्द्रमसे नमः", mean: "Om Som Somaya Namah — Salutation to Soma, the nectar-giver.", count: "11,000 times total or 108 times daily for 11 Mondays" },
    timing: [
      { l: "Sacred Day", v: "Monday (Somvar)" },
      { l: "Best Tithi", v: "Purnima (full moon) — most potent" },
      { l: "Nakshatra", v: "Rohini, Hasta, Shravana" },
      { l: "Time", v: "Evening — after sunset for full moon puja" },
      { l: "Month", v: "Shravan — Moon-Shiva month" },
      { l: "Color", v: "White — wear white or silver" },
    ],
    gem: { stone: "Pearl (Moti)", alt: "Moonstone or White Coral", metal: "Silver", finger: "Little finger (right hand)", when: "Monday of Shukla Paksha after sunrise" },
    daan: "Donate on Mondays: white rice, milk, curd, white cloth, silver, conch shell, camphor, white flowers. Feed kheer (rice pudding) to Brahmins on Purnima. Give milk to the poor.",
    remedies: [
      { i: "🥛", t: "Milk Offering to Shiva", d: "Offer raw milk to Shiva Linga on Mondays while chanting \"Om Namah Shivaya.\" The single most effective Chandra Dosha remedy." },
      { i: "🌊", t: "Sea or River Immersion", d: "On Purnima, immerse yourself in a river or the sea — this directly releases emotional karmic patterns held in the body." },
      { i: "🌕", t: "Moon Gazing Meditation", d: "On Purnima, gaze at the full moon for 10 minutes while chanting \"Om Som Somaya Namah.\"" },
      { i: "👩", t: "Honor Your Mother", d: "Seek your mother's blessings sincerely. Chandra Dosha is deeply connected to the mother relationship." },
    ],
    joy: [
      { i: "😌", t: "Emotional Peace", d: "Mind calms — anxiety dissolves into deep inner stillness" },
      { i: "😴", t: "Restful Sleep", d: "Sweet dreams and deep, restorative sleep restored" },
      { i: "💞", t: "Emotional Warmth", d: "Capacity for genuine love and intimacy returns" },
      { i: "🌸", t: "Mother's Blessings", d: "Maternal love and ancestral feminine grace flow" },
    ],
  },
  // ── MARS ──
  {
    id: "mangal-dosha", category: "mars", name: "Mangal Dosha (Kuja Dosha)", sanskrit: "मांगलिक दोष",
    icon: "🔴", planetLabel: "Mangal — Mars",
    colors: { art: "linear-gradient(135deg,#2d0000,#500000)", accent: "#d83434", badge: "#CC0000" },
    severity: { dosha: 80, health: 60, career: 65, relations: 90 },
    shortDesc: "The most famous dosha — Mars in houses 1, 2, 4, 7, 8, or 12 from the Lagna, Moon, or Venus creates turbulence in marriage and relationships. Roughly 40% of people have some form of Mangal Dosha.",
    what: "Mangal Dosha (also called Kuja or Manglik Dosha) forms when Mars occupies the 1st, 2nd, 4th, 7th, 8th, or 12th house from the Lagna (ascendant), Moon, or Venus. Mars is the planet of energy, aggression, action, and desire. In these positions, its fierce energy disrupts the harmony of relationships — particularly marriage. The 7th house (partnership) and 8th house (longevity of spouse) are the most sensitive placements.",
    why: "Mars represents the warrior-self — the part of us that fights, defends, and asserts. When this energy is unchecked in the marriage houses, it creates conflict, dominance, and impulsiveness. Vedic tradition says Mangal Dosha is the imprint of a past life where one misused power in intimate relationships. The remedy is channeling Mars' energy into righteous action.",
    effects: [
      { i: "💔", t: "Turbulent marriage — frequent fights, separation, divorce" },
      { i: "👫", t: "Delay in finding a life partner; repeated broken engagements" },
      { i: "⚠️", t: "In severe cases: threat to spouse's health or lifespan" },
      { i: "🔥", t: "Uncontrolled anger, impulsiveness, and aggressive behavior" },
      { i: "🩸", t: "Blood-related health issues, accidents, surgical operations" },
      { i: "🏠", t: "Domestic conflict — heated home environment" },
    ],
    puja: { name: "Mangal Shanti Puja & Hanuman Puja", detail: "The primary remedy for Mangal Dosha is Hanuman Puja — because Hanuman (the deity of Mars) perfectly channels Mars' energy into selfless service. Visit Hanuman temples on Tuesdays and offer sindoor. Perform the Mangal Shanti Puja — a Vedic homam where the Mangal mantra is chanted 10,000 times with offerings of masoor dal (red lentils), red flowers, and red cloth into the sacred fire. The Mangal Chandika Stotra is also highly effective." },
    mantra: { san: "ॐ क्रां क्रीं क्रौं सः भौमाय नमः | ॐ अंगारकाय नमः", mean: "Om Kraam Kreem Kraum Sah Bhaumaya Namah — Salutation to Mars, son of Earth.", count: "10,000 times total or 108 times daily for 21 Tuesdays" },
    timing: [
      { l: "Sacred Day", v: "Tuesday (Mangalvar)" },
      { l: "Best Tithi", v: "Chaturthi or Krishna Ashtami" },
      { l: "Nakshatra", v: "Mrigashira, Chitra, Dhanishtha" },
      { l: "Time", v: "Morning — within first 3 hours of sunrise" },
      { l: "Temple", v: "Srikalahasti (AP), Mangal temples" },
      { l: "Color", v: "Red — wear red on Tuesdays" },
    ],
    gem: { stone: "Red Coral (Moonga)", alt: "Red Carnelian (weaker)", metal: "Copper or gold", finger: "Ring finger (right hand)", when: "Tuesday of Shukla Paksha at sunrise after consultation" },
    daan: "Donate on Tuesdays: red lentils (masoor dal), red cloth, copper vessel, jaggery, red flowers, blood donation (a powerful Mars remedy). Feed wheat and red items to the poor.",
    remedies: [
      { i: "💪", t: "Channel Mars Productively", d: "Exercise vigorously, practice martial arts, engage in physical discipline. Mars' energy MUST have a positive outlet." },
      { i: "🙏", t: "Kumbh Vivah (if unmarried)", d: "A ritual \"marriage\" to a peepal tree or banana plant before the human wedding — absorbs the Mangal Dosha impact symbolically." },
      { i: "🤝", t: "Marry Another Manglik", d: "When two Mangliks marry, the doshas cancel each other out — classical Jyotish recommendation." },
      { i: "🕍", t: "Navagraha Mangal Puja", d: "At a Navagraha temple, propitiate the Mars idol with red items, ghee, and mantras every Tuesday for 21 weeks." },
    ],
    joy: [
      { i: "❤️", t: "Harmonious Marriage", d: "Deep partnership built on respect instead of conflict" },
      { i: "⚡", t: "Channeled Energy", d: "Immense Mars vitality becomes a gift, not a curse" },
      { i: "🏆", t: "Success & Courage", d: "Natural warrior-energy creates achievement" },
      { i: "🌹", t: "Passionate Love", d: "Mars' fire warms the relationship beautifully" },
    ],
  },
  // ── MERCURY ──
  {
    id: "budh-dosha", category: "mercury", name: "Budh Dosha", sanskrit: "बुध दोष",
    icon: "💚", planetLabel: "Budh — Mercury",
    colors: { art: "linear-gradient(135deg,#0a3a0a,#0f5a0f)", accent: "#2e9e2e", badge: "#32CD32" },
    severity: { dosha: 55, health: 50, career: 70, relations: 55 },
    shortDesc: "Mercury afflicted in the birth chart — causing communication problems, speech defects, learning difficulties, business failures, and nervous system disorders.",
    what: "Budh Dosha arises when Mercury is debilitated (Pisces/Meena), placed in the 6th, 8th, or 12th house, or conjunct malefics (Saturn, Rahu, Ketu, or a very powerful Mars). Mercury governs intelligence, communication, trade, nervous system, and skill. An afflicted Mercury creates a gap between the mind's potential and its expression.",
    why: "Mercury in Jyotish represents Vak Shakti — the power of speech and the formulation of thought. Speech is a divine faculty (Devi Saraswati's domain). When Mercury is afflicted, the soul is working through past-life karma around deception, communication misuse, broken promises, or unethical business practices.",
    effects: [
      { i: "💬", t: "Speech disorders — stammering, inability to communicate clearly" },
      { i: "📚", t: "Learning disabilities, difficulty concentrating, poor memory" },
      { i: "💼", t: "Business failures, dishonest partners, broken agreements" },
      { i: "🧠", t: "Nervous system disorders — anxiety, OCD, compulsive thinking" },
      { i: "✍️", t: "Writing and expression difficulties" },
      { i: "👥", t: "Misunderstandings in relationships — words cause pain unintentionally" },
    ],
    puja: { name: "Budh Graha Puja & Saraswati Aradhana", detail: "The primary Budh remedy is the worship of Lord Ganesha and Goddess Saraswati — who govern wisdom and communication. On Wednesdays, visit a Ganesha temple and offer durva grass (21 blades). At home, perform Budh Puja with green moong dal, green cloth, and green flowers. The Budh Graha Homam — with 9,000 repetitions of the Mercury mantra — is the most intensive remedy." },
    mantra: { san: "ॐ बुं बुधाय नमः | ॐ ब्रां ब्रीं ब्रौं सः बुधाय नमः", mean: "Om Bum Budhaya Namah — Salutation to Mercury, the wise.", count: "9,000 times total or 108 times daily for 9 Wednesdays" },
    timing: [
      { l: "Sacred Day", v: "Wednesday (Budhvar)" },
      { l: "Best Tithi", v: "Panchami (5th) — Mercury's day" },
      { l: "Nakshatra", v: "Ashlesha, Jyeshtha, Revati" },
      { l: "Time", v: "Morning — Mercury strongest at dawn" },
      { l: "Special", v: "Gandmool Shanti if born in Budh/Ketu nakshatra" },
      { l: "Color", v: "Green — wear green on Wednesdays" },
    ],
    gem: { stone: "Emerald (Panna)", alt: "Green Tourmaline or Jade", metal: "Gold or copper", finger: "Little finger (right hand)", when: "Wednesday morning after proper consultation" },
    daan: "Donate on Wednesdays: green moong dal, green vegetables, green cloth, books, pens, educational materials to students. Feed cows green fodder. Support children's education.",
    remedies: [
      { i: "📖", t: "Vedic Education & Study", d: "Mercury loves learning. Studying scriptures, mathematics, or any skill strengthens Mercury." },
      { i: "🤝", t: "Ethical Business Conduct", d: "Mercury rules commerce. Absolute honesty in all dealings is a non-negotiable behavioral remedy." },
      { i: "🌿", t: "Feed Green Items to Cows", d: "On Wednesdays, feed green grass and spinach to cows — this directly propitiates Budha." },
      { i: "✍️", t: "Saraswati Vandana Daily", d: "Chant the Saraswati Vandana every morning — \"Ya Kundendu Tusharahara Dhavala.\"" },
    ],
    joy: [
      { i: "🗣️", t: "Eloquence & Wit", d: "Words flow beautifully — communication becomes a gift" },
      { i: "💡", t: "Sharp Intelligence", d: "Memory, quick thinking, and clarity amplified" },
      { i: "💰", t: "Business Prosperity", d: "Mercury's blessing creates commercial success" },
      { i: "🎓", t: "Academic Excellence", d: "Learning becomes effortless and joyful" },
    ],
  },
  // ── JUPITER ──
  {
    id: "guru-dosha", category: "jupiter", name: "Guru Dosha (Brahaspati Dosha)", sanskrit: "गुरु दोष",
    icon: "⭐", planetLabel: "Guru — Jupiter",
    colors: { art: "linear-gradient(135deg,#2a2200,#473a00)", accent: "#D4A017", badge: "#DAA520" },
    severity: { dosha: 60, health: 55, career: 65, relations: 70 },
    shortDesc: "Jupiter weakened or afflicted — reducing wisdom, blessings of children, financial prosperity, spiritual growth, and the positive guidance of teachers and mentors.",
    what: "Guru Dosha occurs when Jupiter is debilitated (Capricorn/Makara), placed unfavorably, or afflicted by Rahu, Ketu, Saturn, or Mars. Jupiter is the Guru of the gods — the planet of wisdom, expansion, grace, children, dharma, and good fortune. A weak Jupiter reduces one's capacity to receive blessings, recognize teachers, and attract prosperity.",
    why: "Jupiter represents the teacher-student relationship and the soul's accumulated wisdom. Guru Dosha indicates karma around the rejection of wisdom or teachers in past lives, or misuse of divine knowledge — a karmic \"debt of dharma.\"",
    effects: [
      { i: "🧒", t: "Delayed or no children; difficulties with pregnancy" },
      { i: "💸", t: "Financial losses, missed wealth opportunities, poor investments" },
      { i: "🎓", t: "Lack of spiritual wisdom; poor relationship with teachers and gurus" },
      { i: "⚖️", t: "Legal problems, disputes, unethical circumstances" },
      { i: "😞", t: "Pessimism and lack of faith; difficulty believing in a positive future" },
      { i: "📉", t: "Career plateau — inability to grow beyond a certain level" },
    ],
    puja: { name: "Guru Puja & Brihaspati Stotra", detail: "The primary remedy is Guru Puja on Thursdays — the day of Jupiter. Offer yellow flowers (turmeric, marigold), yellow sweets (besan laddoo), turmeric, and banana. The Brihaspati Stotra from the Skanda Purana is chanted 108 times. Visit a Vishnu temple on Thursdays. Wearing yellow, eating saffron rice, and touching the feet of genuine teachers are powerful behavioral remedies." },
    mantra: { san: "ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः | ॐ बृहस्पतये नमः", mean: "Om Graam Greem Graum Sah Gurave Namah — Salutation to Jupiter, the preceptor of the gods.", count: "19,000 times total or 108 times daily for 19 Thursdays" },
    timing: [
      { l: "Sacred Day", v: "Thursday (Guruvar)" },
      { l: "Best Tithi", v: "Purnima (full moon)" },
      { l: "Nakshatra", v: "Punarvasu, Vishakha, Purva Bhadra" },
      { l: "Time", v: "Morning — first hora of the day" },
      { l: "Color", v: "Yellow — wear yellow on Thursdays" },
      { l: "Special", v: "Guruvayur, Tirupati, Brihaspati temples" },
    ],
    gem: { stone: "Yellow Sapphire (Pukhraj)", alt: "Yellow Topaz or Citrine", metal: "Gold", finger: "Index finger (right hand)", when: "Thursday morning of Shukla Paksha after consultation" },
    daan: "Donate on Thursdays: yellow items — turmeric, yellow gram dal (chana dal), yellow cloth, books, gold, sweets to Brahmins. Feed yellow fruits to the poor. Support education and spiritual learning.",
    remedies: [
      { i: "🙏", t: "Seva to Guru & Elders", d: "Sincerely serve and respect teachers, gurus, and wise elders — the most direct Guru remedy." },
      { i: "📿", t: "Wear Yellow", d: "Wear yellow on Thursdays. Use yellow thread (mauli) or yellow sapphire as prescribed." },
      { i: "🍌", t: "Banana Tree Worship", d: "Water the banana tree on Thursdays. Offer turmeric and tie yellow thread around it." },
      { i: "🌿", t: "Avoid Vanity & Ego", d: "Jupiter's opposite is false ego. Practice genuine humility — drop one pride-based behavior each Thursday." },
    ],
    joy: [
      { i: "👶", t: "Blessings of Children", d: "Children come with Jupiter's grace — family expands joyfully" },
      { i: "💰", t: "True Prosperity", d: "Financial abundance arrives aligned with dharma" },
      { i: "🧘", t: "Spiritual Wisdom", d: "Deep understanding of life's purpose flows naturally" },
      { i: "🎯", t: "Right Decisions", d: "Jupiter's guidance ensures choices lead to growth" },
    ],
  },
  // ── VENUS ──
  {
    id: "shukra-dosha", category: "venus", name: "Shukra Dosha", sanskrit: "शुक्र दोष",
    icon: "💗", planetLabel: "Shukra — Venus",
    colors: { art: "linear-gradient(135deg,#3d0025,#5a0038)", accent: "#d6418c", badge: "#FF1493" },
    severity: { dosha: 60, health: 55, career: 55, relations: 80 },
    shortDesc: "Venus weakened or afflicted — creating dissatisfaction in love and marriage, creative blocks, financial difficulties, and the inability to experience joy and beauty in life.",
    what: "Shukra Dosha arises when Venus is debilitated (Virgo/Kanya), placed in the 6th, 8th, or 12th house, or afflicted by Saturn, Rahu, Ketu, or the Sun. Venus governs love, luxury, aesthetics, music, art, marriage, and comfort. When Shukra is afflicted, life loses its sweetness.",
    why: "Venus carries the energy of Lakshmi — the goddess of beauty and abundance. When Venus is afflicted, the soul is working through karma around misuse of pleasure, indulgence, or disrespect of women and the divine feminine in past lives. The remedy requires cultivating genuine appreciation for beauty and supporting women.",
    effects: [
      { i: "💔", t: "Unhappy marriage; inability to maintain romantic relationships" },
      { i: "🎨", t: "Creative blocks; inability to appreciate or create beauty" },
      { i: "💸", t: "Poverty consciousness; difficulty with luxury and financial ease" },
      { i: "😞", t: "Lack of joy, pleasure, and enjoyment in life — anhedonia" },
      { i: "👩", t: "Troubled relationships with women; disrespect of feminine energy" },
      { i: "💊", t: "Reproductive health issues, hormonal imbalances, skin problems" },
    ],
    puja: { name: "Shukra Puja & Mahalakshmi Archana", detail: "The primary remedy is the worship of Goddess Lakshmi on Fridays — Shukra's day. Perform Lakshmi Ashtothara (108 names of Lakshmi) with lotus flowers and perfumed water. The Shukra Puja includes white flowers, curd, silver, white sandalwood, and white cloth. On all Fridays, maintain cleanliness, wear white or pink, and offer perfume to the deity." },
    mantra: { san: "ॐ द्रां द्रीं द्रौं सः शुक्राय नमः | ॐ शुं शुक्राय नमः", mean: "Om Draam Dreem Draum Sah Shukraya Namah — Salutation to Venus, the bright and pure.", count: "16,000 times total or 108 times daily for 16 Fridays" },
    timing: [
      { l: "Sacred Day", v: "Friday (Shukravar)" },
      { l: "Best Tithi", v: "Ashtami (8th)" },
      { l: "Nakshatra", v: "Bharani, Purva Phalguni, Purva Ashadha" },
      { l: "Time", v: "Evening — Venus visible after sunset" },
      { l: "Color", v: "White or pink — wear on Fridays" },
      { l: "Special", v: "Varalakshmi Puja, Mangala Gauri temples" },
    ],
    gem: { stone: "Diamond (Heera)", alt: "White Sapphire or White Zircon", metal: "Silver or platinum", finger: "Middle finger", when: "Friday morning after proper consultation with Jyotishi" },
    daan: "Donate on Fridays: white rice, curd, silver, white flowers, white cloth, scents/perfumes, sweets to women. Feed white items to cows. Support women's welfare and the arts.",
    remedies: [
      { i: "🌸", t: "Worship Women", d: "Serve women sincerely — especially mothers and elderly women. The single most powerful Shukra remedy." },
      { i: "🪷", t: "Lotus Offering to Lakshmi", d: "Every Friday, place a white or pink lotus before a Lakshmi image and offer camphor deepa." },
      { i: "🎵", t: "Cultivate Art & Music", d: "Learn or practice music, dance, painting. Venus thrives through the arts." },
      { i: "✨", t: "Maintain Beauty & Cleanliness", d: "Keep yourself and your home beautiful and clean. Venus responds to personal care and aesthetics." },
    ],
    joy: [
      { i: "💕", t: "Deep Love", d: "Genuine, fulfilling love relationship manifests beautifully" },
      { i: "🎭", t: "Creative Joy", d: "Artistic expression flows freely — life becomes beautiful" },
      { i: "💎", t: "Abundance", d: "Luxury and comfort arrive as Lakshmi's blessings" },
      { i: "🌺", t: "Life's Sweetness", d: "Joy, pleasure, and sensory delight return to daily life" },
    ],
  },
  // ── SATURN ──
  {
    id: "shani-dosha", category: "saturn", name: "Shani Dosha & Sade Sati", sanskrit: "शनि दोष — साढ़े साती",
    icon: "🪐", planetLabel: "Shani — Saturn",
    colors: { art: "linear-gradient(135deg,#0f0f18,#1d1d2e)", accent: "#7a7a92", badge: "#696969" },
    severity: { dosha: 85, health: 75, career: 80, relations: 70 },
    shortDesc: "The most feared planetary influence — Saturn's transit over the natal Moon (Sade Sati — 7.5 years) or malefic Saturn placement creates delays, deprivation, chronic hardship, and karmic reckoning.",
    what: "Shani Dosha has several forms: (1) Natal — Saturn in the 1st, 4th, 7th, 8th, or 12th house causes chronic challenges. (2) Sade Sati — Saturn transiting the 12th, 1st, and 2nd house from natal Moon, a 7.5-year period of intense karmic testing. (3) Shani Mahadasha — the 19-year major period in the Vimshottari dasha. (4) Kantaka Shani — Saturn transiting the 1st, 4th, 7th, or 10th from natal Moon.",
    why: "Shani is called \"Danda-Adhipati\" (lord of punishment) but also \"Nyaya-Devata\" (the god of justice). Saturn delivers the exact consequences of past actions. In the BPHS, Shani represents service, discipline, karmic debt, and detachment. Shani Dosha is the universe ensuring karmic accounts are settled before the soul can advance — the most spiritually significant dosha.",
    effects: [
      { i: "⏳", t: "Extreme delays in career, marriage, and life goals" },
      { i: "💼", t: "Job loss, business failure, prolonged unemployment" },
      { i: "⚖️", t: "Legal troubles, court cases, imprisonment (extreme cases)" },
      { i: "😰", t: "Depression, chronic fatigue, existential despair" },
      { i: "🏥", t: "Chronic illness, bone disorders, teeth problems" },
      { i: "🔒", t: "Feeling trapped, stagnant, unable to move forward despite effort" },
    ],
    puja: { name: "Shani Puja, Rudrabhishek & Shani Shanti Homam", detail: "The primary remedy is the propitiation of Lord Saturn through: (1) Regular Shani Puja every Saturday, (2) Rudrabhishek on Saturdays and Mondays — Shiva is Shani's master and can mitigate his severity, (3) Shani Shanti Homam — 23,000 repetitions of the Shani mantra into sacred fire, (4) Visit Shani Shingnapur (Maharashtra) or Tirunallar (Tamil Nadu). The Hanuman Chalisa reduces Saturn's effects because Shani blessed Hanuman after Hanuman humbled him." },
    mantra: { san: "ॐ शं शनैश्चराय नमः | ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः", mean: "Om Sham Shanaischaraya Namah — Salutation to the slow-moving Saturn.", count: "23,000 times total or 108 times daily for 23 Saturdays" },
    timing: [
      { l: "Sacred Day", v: "Saturday (Shanivar)" },
      { l: "Best Tithi", v: "Amavasya on Saturday — most potent" },
      { l: "Nakshatra", v: "Pushya, Anuradha, Uttara Bhadra" },
      { l: "Special", v: "Shani Jayanti (Jyeshtha Amavasya)" },
      { l: "Shingnapur", v: "Most powerful Shani temple — Maharashtra" },
      { l: "Tirunallar", v: "South India's premier Shani temple" },
    ],
    gem: { stone: "Blue Sapphire (Neelam)", alt: "Amethyst or Lapis Lazuli (weaker)", metal: "Iron or steel (Panchadhatu)", finger: "Middle finger (right hand)", when: "EXTREME CAUTION — test for 3 days before wearing. Consult an experienced Jyotishi." },
    daan: "Donate on Saturdays: black sesame (til), urad dal, mustard oil, black cloth, iron, black blankets to the poor. Feed crows (Shani's vehicle). Light a sesame oil lamp under a peepal tree on Saturday evenings.",
    remedies: [
      { i: "🕍", t: "Hanuman Chalisa — 7x on Saturdays", d: "The most widely practiced Shani remedy — Hanuman humbled Shani and earned his promise not to trouble Hanuman's devotees." },
      { i: "🌿", t: "Peepal Tree Worship", d: "Every Saturday evening, light 7 sesame oil lamps under a peepal tree and circumambulate it 7 times." },
      { i: "🖤", t: "Service to the Disadvantaged", d: "Saturn governs laborers and the marginalized. Genuine service to these groups directly pleases Shani." },
      { i: "🍖", t: "Feed Crows & Black Dogs", d: "Shani's vehicles are the crow and the dog. Feeding them on Saturdays is among the oldest Shani remedies." },
    ],
    joy: [
      { i: "🏆", t: "Hard-Won Success", d: "After Shani's lessons: unshakeable, lasting achievement" },
      { i: "🧘", t: "Deep Wisdom", d: "Saturn's trials create profound understanding of life" },
      { i: "🌟", t: "Karmic Freedom", d: "Old debts settled — soul moves forward unencumbered" },
      { i: "⚖️", t: "True Justice", d: "Right things happen at the right time — no longer delayed" },
    ],
  },
  // ── RAHU ──
  {
    id: "rahu-dosha", category: "rahu", name: "Rahu Dosha", sanskrit: "राहु दोष",
    icon: "🐍", planetLabel: "Rahu — North Node of Moon",
    colors: { art: "linear-gradient(135deg,#1a0033,#2a0050)", accent: "#9370DB", badge: "#4B0082" },
    severity: { dosha: 75, health: 65, career: 60, relations: 65 },
    shortDesc: "Rahu — the shadowy north node of the Moon — creates obsession, illusion, sudden upheaval, and karmic acceleration when strongly afflicted in the birth chart.",
    what: "Rahu is not a physical planet but the point where the Moon's orbit crosses the ecliptic — the \"head of the cosmic serpent.\" Rahu Dosha occurs when Rahu is in an unfavorable house (especially 1st, 4th, 7th, 8th, or 12th), conjunct the Sun or Moon (Grahan/Eclipse Dosha), or afflicting benefics. Rahu amplifies whatever it touches — making material desires overwhelming.",
    why: "According to the Bhagavata Purana, Rahu is the severed head of the demon Svarbhanu who drank the amrit during the churning of the ocean. Vishnu severed his head, but it remained immortal. Rahu represents the unquenched thirst — the desire that can never be permanently satisfied by material means. Rahu Dosha is the karmic lesson that fulfillment cannot come from the external world alone.",
    effects: [
      { i: "🌀", t: "Confusion, illusion, and inability to distinguish truth from Maya" },
      { i: "🤯", t: "Obsessive behavior, addictions, excessive materialism" },
      { i: "⚡", t: "Sudden, unexpected upheavals — loss of everything in an instant" },
      { i: "👻", t: "Paranoia, phobias, irrational fears, sleep paralysis" },
      { i: "💊", t: "Mysterious illnesses that confound doctors; psychosomatic disorders" },
      { i: "🔮", t: "Susceptibility to black magic, evil eye (nazar), and dark energies" },
    ],
    puja: { name: "Rahu Puja & Kaal Sarp Nivaran at Srikalahasti", detail: "The primary Rahu remedy is worship at Srikalahasti Temple (Andhra Pradesh) — one of India's most powerful temples for Rahu-Ketu dosha. Rahu is appeased through offerings to Lord Bhairava (a form of Shiva), Goddess Durga, and the Naga Devata. Rahu Puja includes blue flowers, blue cloth, hessonite (gomed), and offerings to snakes. During Rahu Kaal (the 90-minute daily period Rahu governs), avoid important activities and instead light a lamp or meditate." },
    mantra: { san: "ॐ रां राहवे नमः | ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः", mean: "Om Raam Rahave Namah — Salutation to Rahu, the ascending node.", count: "18,000 times total or 108 times daily for 18 Saturdays" },
    timing: [
      { l: "Sacred Day", v: "Saturday & Wednesday at Rahu Kaal" },
      { l: "Special", v: "Rahu Kaal (90 min) on Saturdays" },
      { l: "Nakshatra", v: "Ardra, Swati, Shatabhisha" },
      { l: "Eclipse", v: "Avoid actions at eclipses; intensify mantras" },
      { l: "Nag Panchami", v: "Especially potent — Shravan Shukla 5th" },
      { l: "Direction", v: "Southwest — Rahu's direction" },
    ],
    gem: { stone: "Hessonite (Gomed)", alt: "Zircon (Jarkan)", metal: "Panchaloha (5-metal alloy)", finger: "Middle finger (right hand)", when: "Saturday during Rahu Kaal after Jyotishi consultation — requires extreme care" },
    daan: "Donate: blue or black sesame, blue cloth, lead items, coconut, blankets to the poor on Saturdays. Feed stray dogs. Donate to organizations helping the marginalized. Offer milk to a Nag (snake) statue.",
    remedies: [
      { i: "🐍", t: "Nag Puja on Nag Panchami", d: "Worship of the serpent deity on Nag Panchami is the most powerful annual Rahu remedy. Offer milk to a Nag idol or anthill." },
      { i: "🕍", t: "Srikalahasti Rahu Puja", d: "Visit Srikalahasti Temple (Andhra Pradesh). The Rahu-Ketu puja here is considered the most potent." },
      { i: "🌿", t: "Feed & Protect Snakes", d: "Never harm snakes. Plant a tulsi at home for Rahu's appeasement." },
      { i: "🧘", t: "Meditation on Detachment", d: "Rahu feeds on material obsession. Even 10 minutes of daily meditation counters Rahu's illusion." },
    ],
    joy: [
      { i: "🌟", t: "Sudden Fortune", d: "When Rahu is appeased: extraordinary, unexpected gifts from life" },
      { i: "🔮", t: "Spiritual Insight", d: "Rahu's illusion lifts — reality seen clearly for the first time" },
      { i: "⚡", t: "Innovative Genius", d: "Rahu's energy becomes creative genius and breakthrough" },
      { i: "🌺", t: "Freedom from Maya", d: "Liberation from material obsession; genuine inner peace" },
    ],
  },
  // ── KETU ──
  {
    id: "ketu-dosha", category: "ketu", name: "Ketu Dosha", sanskrit: "केतु दोष",
    icon: "☄️", planetLabel: "Ketu — South Node of Moon",
    colors: { art: "linear-gradient(135deg,#201500,#3a2800)", accent: "#CD853F", badge: "#8B4513" },
    severity: { dosha: 65, health: 60, career: 55, relations: 60 },
    shortDesc: "Ketu — the headless tail of the cosmic serpent — creates spiritual confusion, sudden losses, health mysteries, and a sense of otherworldliness when afflicted.",
    what: "Ketu is the \"tail of the cosmic serpent\" — the south node of the Moon. Unlike Rahu's material obsession, Ketu creates spiritual confusion, renunciation, and loss of tangible things. Ketu Dosha occurs when Ketu is in the 1st, 2nd, 4th, 7th, 8th, or 12th house, conjunct the Moon, or afflicting luminaries. Ketu rules past-life accumulated wisdom.",
    why: "Ketu represents the \"tail without a head\" — spirituality without the capacity to articulate it, wisdom without worldly grounding. Ketu Dosha often indicates that the soul developed extraordinary spiritual gifts in past lives but must now integrate them into practical, embodied life. It creates detachment — which can manifest as enlightenment or isolation.",
    effects: [
      { i: "🌫️", t: "Feeling of detachment from life — \"not really here\"" },
      { i: "🏥", t: "Mysterious illnesses with no clear diagnosis; psychic sensitivity" },
      { i: "💸", t: "Sudden material losses — money, property, relationships disappear" },
      { i: "🧠", t: "Spiritual confusion; inability to follow any path consistently" },
      { i: "👁️", t: "Hyper-sensitivity, anxiety about the physical world" },
      { i: "🌌", t: "Vivid dreams, encounters with the subtle/spiritual world" },
    ],
    puja: { name: "Ketu Puja & Ganesha Aradhana", detail: "Ketu is associated with Ganesha. The primary remedy is Ganesha Puja on Wednesdays and Chaturthi. Ketu Puja includes brown or multi-colored cloth, cat's eye (Vaidurya) gemstone, sesame, and offerings to flag poles (ketu means flag). The Ketu Graha Shanti Homam — 7,000 repetitions of the Ketu mantra — is performed at specialized Navagraha temples." },
    mantra: { san: "ॐ केतवे नमः | ॐ स्रां स्रीं स्रौं सः केतवे नमः", mean: "Om Ketave Namah — Salutation to Ketu, the flag-bearer.", count: "7,000 times total or 108 times daily for 7 Saturdays" },
    timing: [
      { l: "Sacred Day", v: "Tuesday and Saturday" },
      { l: "Best Tithi", v: "Chaturdashi (14th)" },
      { l: "Nakshatra", v: "Ashwini, Magha, Moola" },
      { l: "Gandmool", v: "Born in Ketu nakshatra? Gandmool Shanti essential" },
      { l: "Temple", v: "Srikalahasti — most powerful for Ketu" },
      { l: "Direction", v: "Northwest — Ketu's direction" },
    ],
    gem: { stone: "Cat's Eye (Lehsunia/Vaidurya)", alt: "Chrysoberyl Cat's Eye", metal: "Panchaloha", finger: "Middle finger", when: "Tuesday after Jyotishi consultation — needs expert guidance" },
    daan: "Donate: sesame seeds, blankets, multi-colored cloth, brown or maroon items, shoes to the poor on Tuesdays. Feed street dogs. Support spiritual organizations and monasteries.",
    remedies: [
      { i: "🐘", t: "Ganesha Puja on Chaturthi", d: "Monthly Sankashti Chaturthi puja for Ganesha addresses Ketu Dosha at the root — Ganesha and Ketu share wisdom beyond conventional form." },
      { i: "🔱", t: "Grounding Practices", d: "Ketu creates floating energy. Walking barefoot on earth, gardening, or exercise dramatically helps." },
      { i: "🐕", t: "Feed & Protect Dogs", d: "Dogs are connected to Ketu's energy. Caring for street dogs, especially on Tuesdays, is a powerful remedy." },
      { i: "🌿", t: "Simplify Life", d: "Ketu's lessons are about non-attachment. Simplifying possessions and desires aligns with Ketu's nature." },
    ],
    joy: [
      { i: "🧘", t: "Spiritual Liberation", d: "Ketu's gift, when resolved, is genuine moksha-orientation" },
      { i: "🔮", t: "Psychic Gifts", d: "Extraordinary intuition and healing abilities emerge" },
      { i: "☮️", t: "Deep Peace", d: "Ketu's detachment becomes serene non-attachment" },
      { i: "🌟", t: "Past-Life Gifts", d: "Ancient soul wisdom flows freely into this life" },
    ],
  },
  // ── COMPOUND: KAAL SARP ──
  {
    id: "kaal-sarp", category: "compound", name: "Kaal Sarp Dosha", sanskrit: "काल सर्प दोष",
    icon: "🐉", planetLabel: "Rahu-Ketu Axis — All 7 Planets Hemmed",
    colors: { art: "linear-gradient(135deg,#0d0020,#1a0040)", accent: "#7B2FBE", badge: "#4B0082" },
    severity: { dosha: 90, health: 70, career: 75, relations: 75 },
    shortDesc: "All seven classical planets hemmed between Rahu and Ketu in the birth chart — creating intense karmic acceleration, repeated obstacles, and a life of profound peaks and depths.",
    what: "Kaal Sarp Dosha forms when all seven visible planets (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn) are placed on one side of the Rahu-Ketu axis. There are 12 types named after the 12 serpents of Hindu mythology (Anant, Kulik, Vasuki, Shankhpal, Padma, Mahapadma, Takshak, Karkotak, Shankhachur, Ghatak, Vishdhar, Sheshnag) — each affecting different houses and life areas.",
    why: "Kaal means \"time\" or \"death\" — Kaal Sarp represents the cosmic serpent of time swallowing all planetary energies. The Skanda Purana describes this as the result of past-life karma involving snakes or serpent deities. The remedy must balance both Rahu (material desire) and Ketu (spiritual renunciation) simultaneously.",
    effects: [
      { i: "⏳", t: "Prolonged delays in every area — success comes late but often intensely" },
      { i: "😰", t: "Vivid dreams of snakes, water, ancestors, or dark spaces" },
      { i: "🔄", t: "Repeated patterns — same type of failure recurring" },
      { i: "💔", t: "Relationship difficulties; often married late or multiple times" },
      { i: "🌊", t: "Life of dramatic highs and crushing lows — rarely moderate" },
      { i: "⚡", t: "Fear, anxiety, and the sense that something is preventing success" },
    ],
    puja: { name: "Kaal Sarp Dosh Nivaran Puja at Trimbakeshwar", detail: "The most revered remedy is the Kaal Sarp Dosh Nivaran Puja at Trimbakeshwar Temple (Nashik, Maharashtra) — one of the 12 Jyotirlingas. Performed by specialized priests, the ritual includes Rudrabhishek, Nag Pratishtha (installing a silver serpent pair), chanting Mahamrityunjaya mantra 1,008 times, and offering milk to the Jyotirlinga. Ujjain Mahakal Temple is the second most powerful location. This puja should be done with full Sankalp by the native in person." },
    mantra: { san: "ॐ नागकुलाय नमः | ॐ नमः शिवाय | महामृत्युञ्जय मंत्र", mean: "Om Nagakulaya Namah — Salutation to the lineage of Nagas. Combined with Om Namah Shivaya and the Mahamrityunjaya Mantra.", count: "Mahamrityunjaya: 1,008 times. Shiva mantra: 108 daily. Nag mantra: 11,000 total" },
    timing: [
      { l: "Best Location", v: "Trimbakeshwar, Ujjain, or Srikalahasti" },
      { l: "Sacred Day", v: "Monday + Saturday combination" },
      { l: "Best Tithi", v: "Nag Panchami (most potent annual day)" },
      { l: "Purnima", v: "Full moon puja most effective" },
      { l: "Lunar Eclipse", v: "Perform special puja — intense Kaal Sarp period" },
      { l: "Avoid", v: "Starting new ventures during Kaal Sarp period" },
    ],
    gem: { stone: "Silver serpent pair (Nag-Nagin)", alt: "Two-faced Rudraksha (Dwitiya)", metal: "Silver for serpent idol", finger: "N/A — kept in puja room, not worn", when: "After Trimbakeshwar puja — the silver Nag-Nagin is installed in the temple or home puja room" },
    daan: "Donate: silver (most important for Kaal Sarp), milk to serpent temples, feed milk to snake anthills, donate to snake-habitat conservation. Release live fish in a river. Offer milk at Nag temples on Nag Panchami.",
    remedies: [
      { i: "🏛️", t: "Trimbakeshwar Puja (Non-Negotiable)", d: "For serious Kaal Sarp Dosha, visiting Trimbakeshwar and performing the puja in person is the definitive remedy." },
      { i: "🌊", t: "Nag Panchami Milk Offering", d: "Every Nag Panchami, offer milk at a serpent temple or anthill. This annual ritual weakens Kaal Sarp over years." },
      { i: "🔱", t: "Rudrabhishek Every Monday", d: "Weekly Rudrabhishek with Shiva mantra, especially through Shravan, reduces Kaal Sarp's grip." },
      { i: "🐍", t: "Silver Nag-Nagin at Home", d: "Keep a silver serpent pair in the northeast of your puja room after consecration. Water with milk on full moon nights." },
    ],
    joy: [
      { i: "🌊", t: "The Wave Breaks", d: "After remedy: success arrives suddenly — Kaal Sarp becomes a yoga of intensity and achievement" },
      { i: "🔮", t: "Spiritual Acceleration", d: "The serpent energy becomes a vehicle for Kundalini awakening" },
      { i: "💎", t: "Exceptional Destiny", d: "Many great leaders had Kaal Sarp — it confers unusual distinction" },
      { i: "☯️", t: "Karmic Freedom", d: "Ancient serpent karma resolved — soul unbounds and soars" },
    ],
  },
  // ── COMPOUND: PITRU ──
  {
    id: "pitru-dosha", category: "compound", name: "Pitru Dosha (Ancestral Karma)", sanskrit: "पितृ दोष",
    icon: "🪔", planetLabel: "Sun + 9th House Affliction — Ancestral Karma",
    colors: { art: "linear-gradient(135deg,#2d1500,#4a2800)", accent: "#DEB887", badge: "#8B6914" },
    severity: { dosha: 80, health: 65, career: 65, relations: 70 },
    shortDesc: "Unresolved ancestral karma causing generational suffering — when the Sun, Moon, or 9th house lord is afflicted by Rahu, Ketu, or Saturn, the unfulfilled desires and incomplete rites of departed ancestors create obstacles in the present.",
    what: "Pitru Dosha (also Pitri/Pitra Dosha) forms when: (1) the Sun (karaka of father) is afflicted, especially by Rahu or Ketu, (2) Rahu is in the 9th house (ancestors and dharma), (3) Saturn and Rahu conjunct in the 5th house (children), (4) the 9th lord is debilitated or in the 6th/8th/12th house. It represents the unfinished spiritual business of ancestors who departed without proper last rites (Shraddha), died violently, or had unfulfilled desires.",
    why: "Hindu tradition teaches that departed ancestors (Pitrus) continue to influence the living if their needs are not met — if Shraddha (memorial rites) and Tarpan (water offerings) are not performed, their unfulfilled desires pass into the family line. The Garuda Purana details how Pitru karma flows through lineages and which doshas indicate which ancestors call for attention.",
    effects: [
      { i: "👶", t: "Difficulty having children; repeated miscarriages; unhealthy offspring" },
      { i: "💼", t: "Career obstacles despite hard work; success always out of reach" },
      { i: "💔", t: "Repeated relationship patterns matching ancestral trauma" },
      { i: "😰", t: "Family members falling ill repeatedly; generational health patterns" },
      { i: "😞", t: "Inexplicable sorrow or depression without external cause" },
      { i: "🏠", t: "No peace in the family home despite material comfort" },
    ],
    puja: { name: "Shraddha, Tarpan & Pind Daan at Gaya", detail: "The most powerful remedy is Pind Daan at Gaya, Bihar — the sacred city where Vishnu's footprint (Vishnupad) is enshrined. Performing Pind Daan (rice ball offerings) at Gaya is said to liberate 21 generations of ancestors. Annually, during Pitru Paksha (16 dark-fortnight days in Ashwin when ancestors visit earth), Shraddha and Tarpan must be performed. Other sacred sites: Trimbakeshwar, Haridwar, Varanasi (Asi Ghat), Prayagraj (Sangam)." },
    mantra: { san: "ॐ पितृभ्यः स्वधा नमः", mean: "Om Pitribhyah Svadha Namah — Salutation and offering to the ancestors. The Tarpan mantra invokes each ancestor by name to be satisfied with sesame-water offerings.", count: "Chanted daily during Pitru Paksha while offering water, or on every Amavasya." },
    timing: [
      { l: "Pitru Paksha", v: "16 days in Bhadrapada/Ashwin (Sept–Oct)" },
      { l: "Amavasya", v: "Every new moon — most potent monthly" },
      { l: "Mahalaya", v: "The most powerful Pitru Paksha day" },
      { l: "Best Location", v: "Gaya, Trimbakeshwar, Prayagraj, Varanasi" },
      { l: "Direction", v: "Face south while performing Tarpan" },
      { l: "2026", v: "Pitru Paksha: October 9–24, 2026" },
    ],
    gem: { stone: "No gemstone for Pitru Dosha", alt: "Two-faced Rudraksha for Sun", metal: "Silver bowl for Tarpan", finger: "N/A", when: "Perform Tarpan, not gemstones, for Pitru Dosha" },
    daan: "During Pitru Paksha, donate: sesame seeds, water, cooked food, cows, gold, silver, clothing, and cash to Brahmins in the name of ancestors. Feed crows (Pitrus come as crows). Cook the ancestors' favorite foods and offer them.",
    remedies: [
      { i: "💧", t: "Daily Tarpan at Home", d: "Every morning (especially Amavasya), offer water from a copper vessel facing south, saying the ancestor's name." },
      { i: "🏛️", t: "Pind Daan at Gaya", d: "The definitive remedy — visit Gaya and perform Pind Daan. Said to liberate all generations of ancestors permanently." },
      { i: "🦅", t: "Feed Crows on Amavasya", d: "Pitrus visit as crows on Amavasya. Set out rice, sesame, and cooked food for crows on every new moon." },
      { i: "🌊", t: "Shraddha at Ganga", d: "On Mahalaya Amavasya, offer Tarpan in the Ganga, Yamuna, or any sacred river." },
    ],
    joy: [
      { i: "👶", t: "Children Arrive", d: "With Pitru Dosha resolved, fertility and healthy children bless the family" },
      { i: "🏠", t: "Home Peace", d: "Generational trauma releases — home becomes genuinely peaceful" },
      { i: "🌟", t: "Career Unblocks", d: "Ancestral support arrives — success flows where it was stuck" },
      { i: "🔗", t: "Ancestral Blessings", d: "Pitrus, satisfied, become protectors and guides of the family line" },
    ],
  },
  // ── COMPOUND: SHRAPIT ──
  {
    id: "shrapit-dosha", category: "compound", name: "Shrapit Dosha", sanskrit: "शापित दोष",
    icon: "⚡", planetLabel: "Saturn + Rahu Conjunction",
    colors: { art: "linear-gradient(135deg,#15002a,#250040)", accent: "#8b3ddb", badge: "#4B0082" },
    severity: { dosha: 85, health: 70, career: 80, relations: 75 },
    shortDesc: "Saturn and Rahu conjunct in the same house — creating the \"cursed\" dosha of extreme bad luck, repeated failures, and life-altering obstacles that seem to arise from nowhere.",
    what: "Shrapit Dosha (literally \"cursed dosha\") forms when Saturn and Rahu are conjunct in the same house. Saturn is the planet of karma and discipline; Rahu is the planet of shadow and intense desire. Together they create a double-weight of karmic reckoning — Saturn's lessons amplified by Rahu's intensity. It can also form when both aspect the same house or planet.",
    why: "The BPHS describes Shrapit Dosha as the result of past-life curses — from Brahmins, gurus, or sages whose wisdom was rejected or who were harmed. \"Shrapit\" literally means \"cursed\" — karmic imprints never resolved that now demand resolution in this lifetime.",
    effects: [
      { i: "💀", t: "Extreme bad luck — efforts come to nothing repeatedly" },
      { i: "🔒", t: "Feeling cursed or trapped despite all remedies" },
      { i: "💔", t: "Very late or no marriage; extreme difficulty maintaining relationships" },
      { i: "😰", t: "Chronic depression, existential crisis, meaninglessness" },
      { i: "💼", t: "Career destruction just as success seems within reach" },
      { i: "⚡", t: "Sudden, inexplicable disasters when life seems settled" },
    ],
    puja: { name: "Shrapit Dosha Nivaran Puja & Maha Rudrabhishek", detail: "The remedy requires both Saturn and Rahu addressed simultaneously. The primary puja is Shrapit Dosha Nivaran Puja — a specialized ritual at Shanishchara or Rahu-Ketu temples with mantras for both planets. Maha Rudrabhishek (11 rounds of abhishek) is extremely effective. The Navagraha Shanti Homam — simultaneous propitiation of all 9 planets — addresses the compound nature. Kedar Ghat (Varanasi) and Trimbakeshwar are the most powerful locations." },
    mantra: { san: "ॐ शं शनैश्चराय नमः + ॐ रां राहवे नमः (combined)", mean: "Alternately chant the Shani and Rahu mantras in a combined 21-mala session. Their dual propitiation is the key to this dosha.", count: "23,000 Shani mantras + 18,000 Rahu mantras in sequence" },
    timing: [
      { l: "Sacred Day", v: "Saturday — both Saturn and Rahu's day" },
      { l: "Special", v: "When Saturn and Rahu transit the natal conjunction sign" },
      { l: "Amavasya", v: "New moon Saturdays — most potent" },
      { l: "Timing", v: "Rahu Kaal on Saturday — extremely potent" },
      { l: "Location", v: "Shani Shingnapur + Srikalahasti (both)" },
      { l: "Duration", v: "Minimum 11 Saturdays of intensive practice" },
    ],
    gem: { stone: "Consult experienced Jyotishi only", alt: "Two-faced or Saptamukhi Rudraksha", metal: "Iron/Steel pendant", finger: "N/A without expert guidance", when: "Do NOT wear gemstones for this dosha without Jyotishi guidance — can intensify" },
    daan: "Most powerful: donate black sesame + mustard oil together on Saturdays. Feed crows AND black dogs the same day. Donate iron utensils and black blankets to laborers. Support both the elderly (Saturn) and immigrants/outsiders (Rahu).",
    remedies: [
      { i: "🕍", t: "Navagraha Havan", d: "A complete Navagraha Havan (fire ritual to all 9 planets) — the most comprehensive remedy for compound doshas like Shrapit." },
      { i: "🌿", t: "Mahakal Ujjain", d: "Visit Mahakaleshwar at Ujjain — the center of time consciousness. The Bhasma Aarti at 4 AM is extraordinarily powerful for Saturn doshas." },
      { i: "📿", t: "108 Days of Shani-Rahu Mantra", d: "108 consecutive days alternating Shani and Rahu mantras, 108 times daily — breaks the karmic pattern at its root." },
      { i: "🤝", t: "Serve Outcasts & Marginalized", d: "Shani + Rahu govern those on society's periphery. Sustained service to the homeless, prisoners, or addicts is the behavioral remedy." },
    ],
    joy: [
      { i: "⚡", t: "Lightning Transformation", d: "When this dosha resolves, the reversal is dramatic and complete" },
      { i: "💪", t: "Unbreakable Resilience", d: "Shrapit survivors are among life's most unshakeable souls" },
      { i: "🌟", t: "Exceptional Destiny", d: "Many with Shrapit Dosha have exceptional, unusual life paths" },
      { i: "🙏", t: "Deep Karmic Freedom", d: "Ancient curses dissolved — soul emerges in fullness" },
    ],
  },
];

export const DOSHA_CATEGORIES = [
  { id: "all", label: "All Doshas" },
  { id: "sun", label: "☀️ Surya" },
  { id: "moon", label: "🌙 Chandra" },
  { id: "mars", label: "🔴 Mangal" },
  { id: "mercury", label: "💚 Budh" },
  { id: "jupiter", label: "⭐ Guru" },
  { id: "venus", label: "💗 Shukra" },
  { id: "saturn", label: "🪐 Shani" },
  { id: "rahu", label: "🐍 Rahu" },
  { id: "ketu", label: "☄️ Ketu" },
  { id: "compound", label: "⚡ Compound" },
];
