// Sacred Pujas of India — full reference data (28 pujas).
// Source: curated Vedic puja compendium (descriptions, Panchang timing,
// significance, samagri, benefits). Used to populate the app's puja catalogue.

export const RAW_PUJAS = [
  // ── SHIVA ──────────────────────────────────────────────
  {
    id: "maha-shivaratri", category: "shiva", featured: true,
    name: "Maha Shivaratri Puja", sanskrit: "महाशिवरात्रि पूजा",
    deity: "Lord Shiva", deityEmoji: "🔱",
    region: "Pan-India", type: "Festival Puja",
    colors: { bg: "linear-gradient(135deg,#3a2a5e,#5a3d8a)", accent: "#7B5EA7", badge: "#9370DB", icon: "#7B5EA7" },
    desc: "The Great Night of Shiva — the most sacred night in the Hindu calendar when Lord Shiva performed the Tandava and the Shivalinga emerged as a pillar of infinite light.",
    when: "Chaturdashi (14th night) of Krishna Paksha in Phalguna month (Feb–March). Most auspicious between midnight and dawn.",
    panchang: [
      { l: "Tithi", v: "Krishna Chaturdashi" },
      { l: "Month", v: "Phalguna / Magha" },
      { l: "Best Time", v: "Nishita Kaal (midnight)" },
      { l: "Nakshatra", v: "Shatabhisha preferred" },
      { l: "Day", v: "Any — but Tuesday ideal" },
      { l: "2026 Date", v: "February 26, 2026" },
    ],
    significance: "Vedic tradition holds that performing Rudrabhishek on this night with milk, honey, ghee, and water — while chanting the Panchakshari mantra \"Om Namah Shivaya\" — destroys all sins accumulated over lifetimes. The Shiva Purana prescribes four prahar (watches) of worship through the night.",
    samagri: "Bilva leaves (most essential), raw milk, honey, ghee, water, panchamrit, ash (vibhuti), rudraksha, white flowers, dhatura, blue-black sesame seeds, camphor, belpatra.",
    benefits: [
      { i: "🧘", t: "Liberation (Moksha)", d: "Attainment of spiritual liberation" },
      { i: "👫", t: "Blessed Marriage", d: "Unmarried women find devoted husbands" },
      { i: "💪", t: "Destruction of Sins", d: "All past karma purified in one night" },
      { i: "🌙", t: "Cosmic Connection", d: "Alignment with Shiva's cosmic energy" },
      { i: "🏥", t: "Health & Longevity", d: "Mahamrityunjaya blessings invoked" },
      { i: "☮️", t: "Inner Peace", d: "Mind freed from fear and anxiety" },
    ],
  },
  {
    id: "rudrabhishek", category: "shiva",
    name: "Rudrabhishek Puja", sanskrit: "रुद्राभिषेक पूजा",
    deity: "Lord Shiva (Rudra)", deityEmoji: "🔱",
    region: "North & South India", type: "Abhishek Puja",
    colors: { bg: "linear-gradient(135deg,#2a2060,#3a2a80)", accent: "#6A5ACD", badge: "#483D8B", icon: "#9B7DFF" },
    desc: "The most powerful Shiva ritual — pouring sacred substances over the Shivalinga while chanting the Rudrashtadhyayi from the Yajur Veda. \"Abhishek\" means consecrated bathing of the deity.",
    when: "Mondays (Shiva's day), Pradosh Vrat (13th tithi), Maha Shivaratri, or any Shukla Paksha. Shravan month is especially potent.",
    panchang: [
      { l: "Best Day", v: "Monday (Somvar)" },
      { l: "Tithi", v: "Trayodashi (Pradosh)" },
      { l: "Month", v: "Shravan (July–Aug)" },
      { l: "Time", v: "Brahma Muhurta (4–6 AM)" },
      { l: "Nakshatra", v: "Ardra, Pushya, Anuradha" },
      { l: "Frequency", v: "Weekly or monthly" },
    ],
    significance: "The Shri Rudram from the Krishna Yajur Veda is the scriptural basis. The 108 names of Shiva (Shatarudriya) are chanted while each substance is poured — each substance removes a specific type of karma.",
    samagri: "Panchamrit (milk, curd, honey, ghee, sugar), gangajal, rose water, bilva patra, ashta gandha, dhatura flowers, chameli, saffron water, coconut water, sugar cane juice.",
    benefits: [
      { i: "🧿", t: "Removes Doshas", d: "Clears Kal Sarp, Pitra, and graha doshas" },
      { i: "💚", t: "Health Restoration", d: "Chronic illness healing amplified" },
      { i: "🏠", t: "Family Harmony", d: "Disputes and conflicts dissolve" },
      { i: "💰", t: "Financial Stability", d: "Obstacles in wealth removed" },
      { i: "🌿", t: "Longevity", d: "Mahamrityunjaya protection invoked" },
      { i: "✨", t: "Spiritual Growth", d: "Kundalini energy awakened" },
    ],
  },
  {
    id: "shiva-puja", category: "shiva",
    name: "Nitya Shiva Puja", sanskrit: "नित्य शिव पूजा",
    deity: "Lord Shiva", deityEmoji: "🔱",
    region: "Pan-India", type: "Daily Puja",
    colors: { bg: "linear-gradient(135deg,#1d3a6b,#2a4a86)", accent: "#4169E1", badge: "#1E90FF", icon: "#87CEEB" },
    desc: "The daily worship of Lord Shiva performed in homes and temples across India. The five elements — earth (pushpa), water (abhishek), fire (deepa), air (dhupa), space (akash puja) — are offered to the formless.",
    when: "Daily, ideally at sunrise and sunset. Mondays are most auspicious. Pradosh time (1.5 hours before sunset on Trayodashi) is especially powerful.",
    panchang: [
      { l: "Best Day", v: "Monday (Somvar)" },
      { l: "Ideal Time", v: "Sunrise & Pradosh Kaal" },
      { l: "Tithi", v: "Any — Trayodashi best" },
      { l: "Month", v: "Shravan especially potent" },
      { l: "Nakshatra", v: "Ardra (Shiva's own)" },
      { l: "Frequency", v: "Daily ideal" },
    ],
    significance: "The Shiva Purana states that one who worships Shiva with bilva leaves is freed from all three types of sins — physical, mental, and verbal. Even a single bilva leaf offered with devotion equals the merit of all pilgrimages.",
    samagri: "Bilva patra, water, milk, honey, vibhuti (sacred ash), rudraksha mala, white flowers, camphor, incense, deepa (lamp).",
    benefits: [
      { i: "🧠", t: "Mental Clarity", d: "Removes confusion and brings wisdom" },
      { i: "😌", t: "Fearlessness", d: "Shiva as Abhayankara removes all fears" },
      { i: "🌊", t: "Emotional Balance", d: "The nature of Shiva brings stillness" },
      { i: "🪷", t: "Detachment", d: "Vairagya (non-attachment) cultivated" },
    ],
  },
  {
    id: "mahamrityunjaya", category: "shiva",
    name: "Mahamrityunjaya Japa", sanskrit: "महामृत्युंजय जप पूजा",
    deity: "Lord Tryambakeshwara (Three-eyed Shiva)", deityEmoji: "🔱",
    region: "Pan-India, especially Varanasi, Nashik (Trimbakeshwar)", type: "Mantra Japa",
    colors: { bg: "linear-gradient(135deg,#241a5e,#34208a)", accent: "#483D8B", badge: "#6A5ACD", icon: "#B0C4DE" },
    desc: "The mantra that conquers death — the Maha Mrityunjaya mantra from the Rigveda (7.59.12) and Yajur Veda is chanted 108, 1008, or 1.25 lakh times. Markandeya Rishi chanted this and transcended death itself.",
    when: "On Maha Shivaratri, Mondays, during serious illness, before surgery, for longevity, or as directed by a guru. The Purnima night is also potent for this japa. Can be performed at any time of need.",
    panchang: [
      { l: "Primary", v: "Maha Shivaratri" },
      { l: "Weekly", v: "Monday (Somvar)" },
      { l: "For Illness", v: "Any time — no muhurta needed" },
      { l: "Count", v: "108, 1008, or 1.25 lakh (siddha)" },
      { l: "Best Place", v: "Varanasi — City of Shiva" },
      { l: "Best Muhurta", v: "Brahma Muhurta (before sunrise)" },
    ],
    significance: "The mantra: \"Om Tryambakam Yajamahe Sugandhim Pushtivardhanam, Urvarukamiva Bandhanan Mrityor Mukshiya Maamritat.\" Translation: \"We worship Tryambaka, the three-eyed one, fragrant, nourishing all beings. Like the ripe cucumber freed from its vine, may we be liberated from death, not from immortality.\" This is the most potent healing mantra in the Vedas.",
    samagri: "Rudraksha mala (108 beads), bilva leaves, white flowers, holy water, sandalwood, ghee lamp, camphor. No elaborate setup needed — the mantra itself is the entire puja.",
    benefits: [
      { i: "🏥", t: "Healing", d: "Chronic and life-threatening illness addressed" },
      { i: "⏳", t: "Longevity", d: "Life extended and vitality restored" },
      { i: "💀", t: "Fear of Death", d: "Mrityu (death) transcended through Shiva's grace" },
      { i: "🧘", t: "Spiritual Liberation", d: "The mantra carries consciousness beyond fear" },
    ],
  },

  // ── VISHNU / VAISHNAVA ─────────────────────────────────
  {
    id: "satyanarayan", category: "vishnu",
    name: "Satyanarayan Puja", sanskrit: "सत्यनारायण पूजा",
    deity: "Lord Vishnu (Satyanarayan)", deityEmoji: "🪷",
    region: "Pan-India (most popular home puja)", type: "Home Puja",
    colors: { bg: "linear-gradient(135deg,#3a5a10,#4d6b18)", accent: "#556B2F", badge: "#6B8E23", icon: "#FFD700" },
    desc: "The most widely performed home puja in India — a thanksgiving ritual to Lord Vishnu in his form as Satyanarayan (Lord of Truth). The Katha (story) describes five devotees whose lives transformed through this puja.",
    when: "On Purnima (full moon) of any month. Also performed after major life events — housewarming, marriage, childbirth, promotion, or completing a vow.",
    panchang: [
      { l: "Best Tithi", v: "Purnima (Full Moon)" },
      { l: "Day", v: "Any — Thursday preferred" },
      { l: "Time", v: "Afternoon (Aparahna)" },
      { l: "Month", v: "Any — especially Kartik" },
      { l: "After Events", v: "New house, job, wedding" },
      { l: "Frequency", v: "Monthly or special occasions" },
    ],
    significance: "Described in the Skanda Purana, this puja is prescribed as the most accessible path to divine grace. Even the poorest man with a handful of flour can perform it. Lord Vishnu, pleased by the simple offering of Panchamrit and Sheera (semolina prasad), grants all desires.",
    samagri: "Panchamrit, banana, tulsi leaves, supari, coconut, flowers, incense, ghee lamp, yellow cloth, yellow thread, semolina for sheera prasad, milk, sugar.",
    benefits: [
      { i: "🏠", t: "Home Prosperity", d: "Peace and abundance in the household" },
      { i: "👨‍👩‍👧", t: "Family Well-being", d: "Health and happiness of all members" },
      { i: "💼", t: "Business Success", d: "New ventures and promotions blessed" },
      { i: "🙏", t: "Vow Fulfillment", d: "Gratitude for desires fulfilled" },
    ],
  },
  {
    id: "vishnu-puja", category: "vishnu",
    name: "Vishnu Sahasranama Puja", sanskrit: "विष्णु सहस्रनाम पूजा",
    deity: "Lord Vishnu", deityEmoji: "🪷",
    region: "Pan-India, especially South India", type: "Archana Puja",
    colors: { bg: "linear-gradient(135deg,#0f3a28,#155040)", accent: "#2E8B57", badge: "#3CB371", icon: "#98FB98" },
    desc: "The chanting of 1,000 divine names of Lord Vishnu from the Mahabharata — a teaching given by Bhishma to Yudhishthira. Each name encapsulates an attribute of the cosmic preserver.",
    when: "Thursdays, Ekadashi, Vaikunta Ekadashi, Kartik Purnima, and any Vishnu festival. Especially during Chaturmas (four sacred months).",
    panchang: [
      { l: "Best Day", v: "Guruvaar (Thursday)" },
      { l: "Tithi", v: "Ekadashi (11th) — most potent" },
      { l: "Month", v: "Kartik — Vishnu's month" },
      { l: "Special", v: "Vaikunta Ekadashi (Dec/Jan)" },
      { l: "Time", v: "Morning — Brahma Muhurta" },
      { l: "Duration", v: "Approx. 45 minutes" },
    ],
    significance: "Bhishma declared in the Anushasana Parva: \"He who reads these names of Vishnu morning, noon and evening, attains that supreme bliss.\" The Padma Purana states that chanting even one name of Vishnu equals the merit of ten thousand years of austerity.",
    samagri: "Tulsi (most sacred to Vishnu), yellow flowers, banana, coconut, yellow rice, panchamrit, sandalwood paste (white), camphor, ghee lamp.",
    benefits: [
      { i: "☮️", t: "Inner Peace", d: "Mind liberated from worry and agitation" },
      { i: "💪", t: "Protection", d: "Vishnu as protector of the universe" },
      { i: "🌟", t: "Moksha Path", d: "Liberation hastened through divine names" },
      { i: "💞", t: "Loving Relationships", d: "Family bonds strengthened" },
    ],
  },
  {
    id: "krishna-janmashtami", category: "vishnu",
    name: "Krishna Janmashtami Puja", sanskrit: "कृष्ण जन्माष्टमी पूजा",
    deity: "Lord Krishna", deityEmoji: "🦚",
    region: "Pan-India, especially Mathura, Vrindavan, Gujarat", type: "Festival Puja",
    colors: { bg: "linear-gradient(135deg,#0a2a6b,#10408a)", accent: "#1E3A8A", badge: "#3B82F6", icon: "#93C5FD" },
    desc: "Celebration of Lord Krishna's birth at midnight on Ashtami of Krishna Paksha in Bhadrapada. The idol of baby Krishna is bathed, dressed, and rocked in a cradle while devotees fast and sing bhajans all night.",
    when: "Ashtami (8th) of Krishna Paksha in Bhadrapada (August–September). Midnight is the exact birth time. Fast is broken only after midnight abhishek.",
    panchang: [
      { l: "Tithi", v: "Krishna Ashtami" },
      { l: "Month", v: "Bhadrapada" },
      { l: "Nakshatra", v: "Rohini (Krishna's birth star)" },
      { l: "Time", v: "Nishita Puja at midnight" },
      { l: "2026 Date", v: "August 26, 2026" },
      { l: "Fast", v: "Nirjala or Phalahara" },
    ],
    significance: "The Bhagavata Purana dedicates the entire 10th Skandha to Krishna's divine life. His birth at midnight, during the darkest moment, symbolizes the advent of divine light at the darkest hour of one's life. Rohini Nakshatra during Ashtami is the most auspicious combination.",
    samagri: "Panchamrit for abhishek, new clothes for idol, flute, peacock feather, makhan (butter), mishri, tulsi, flowers (preferably blue), incense, diya.",
    benefits: [
      { i: "❤️", t: "Divine Love", d: "Bhakti and devotion deepened profoundly" },
      { i: "🎭", t: "Joy & Playfulness", d: "Krishna's Leela brings childlike joy" },
      { i: "🛡️", t: "Protection", d: "Krishna as Govinda protects devotees" },
      { i: "🌺", t: "Spiritual Transformation", d: "Ego dissolved in divine love" },
    ],
  },
  {
    id: "ram-navami", category: "vishnu",
    name: "Ram Navami Puja", sanskrit: "राम नवमी पूजा",
    deity: "Lord Rama", deityEmoji: "🏹",
    region: "Pan-India, especially Ayodhya, Varanasi", type: "Festival Puja",
    colors: { bg: "linear-gradient(135deg,#5a4410,#7a5e14)", accent: "#8B6914", badge: "#DAA520", icon: "#FFD700" },
    desc: "The birth celebration of Lord Rama — the seventh avatar of Vishnu — born to King Dasharatha and Queen Kaushalya in Ayodhya. Rama Navami marks the pinnacle of dharmic conduct and the ideal human.",
    when: "Navami (9th) of Shukla Paksha in Chaitra (March–April). The Madhyahna Muhurta (midday) is the prescribed puja time as Rama was born at noon.",
    panchang: [
      { l: "Tithi", v: "Shukla Navami" },
      { l: "Month", v: "Chaitra" },
      { l: "Best Time", v: "Madhyahna (11 AM–1 PM)" },
      { l: "Nakshatra", v: "Punarvasu (Rama's birth star)" },
      { l: "2026 Date", v: "March 28, 2026" },
      { l: "Lagna", v: "Cancer (Karka) preferred" },
    ],
    significance: "The Ramacharitamanas of Tulsidas prescribes the recitation of the Ram Naam (Rama's name) as the greatest of all sadhanas. A complete reading of the Sundarkand or Bala Kanda on this day brings immense merit.",
    samagri: "Tulsi, lotus flowers, yellow cloth, pancha amrit, gangajal, sindoor, sandalwood, rose petals, ghee deepa, Ramayana book for parayana.",
    benefits: [
      { i: "⚖️", t: "Righteousness", d: "Dharma and moral strength cultivated" },
      { i: "🙏", t: "Ancestor Blessings", d: "Pitru shanti and ancestral merit" },
      { i: "💝", t: "Ideal Relationships", d: "Rama and Sita as ideal partnership" },
      { i: "🌟", t: "Victory", d: "Success in all righteous endeavours" },
    ],
  },
  {
    id: "kuber-puja", category: "vishnu",
    name: "Kuber Puja", sanskrit: "कुबेर पूजा",
    deity: "Lord Kuber (God of Wealth)", deityEmoji: "💰",
    region: "North India, Gujarat", type: "Wealth Puja",
    colors: { bg: "linear-gradient(135deg,#5a4a0a,#7a6410)", accent: "#B8860B", badge: "#FFD700", icon: "#FFFACD" },
    desc: "The worship of Kuber — the treasurer of the gods and lord of Yakshas who guards the eight directional treasures of the universe. He is typically worshipped alongside Lakshmi on Dhanteras (two days before Diwali).",
    when: "Dhanteras (Dhana Trayodashi — 13th of Krishna Paksha in Kartik). Also Fridays, any time a new business or financial venture begins. Especially powerful in the north direction (Kuber's direction).",
    panchang: [
      { l: "Primary", v: "Dhanteras — Kartik Krishna 13" },
      { l: "Weekly", v: "Thursday (Brihaspati's day)" },
      { l: "Direction", v: "North (Kubera's direction)" },
      { l: "2026 Date", v: "October 27, 2026 (Dhanteras)" },
      { l: "With", v: "Lakshmi Puja together" },
      { l: "Buy", v: "New gold, silver, or utensils" },
    ],
    significance: "The Atharvaveda describes Kuber as Naravahana — riding human beings as his vehicle, symbolizing that wealth is carried by human effort and divine grace together. The Kuber Yantra is placed in the north of the puja room. Chanting \"Om Yakshaya Kuberaya Vaishravanaya Dhana Dhanyadi Padaye\" 108 times activates wealth energy.",
    samagri: "Kuber Yantra, gold or silver coins, yellow flowers, yellow cloth, saffron, camphor, ghee lamp, Kuber idol or image, lotus, 9 gems or metal coins.",
    benefits: [
      { i: "💎", t: "Treasure Activation", d: "Hidden wealth and abundance unlocked" },
      { i: "🏦", t: "Business Growth", d: "Commercial success and trade expansion" },
      { i: "💳", t: "Debt Freedom", d: "Outstanding debts resolved through divine flow" },
      { i: "🌟", t: "Financial Security", d: "Long-term wealth stability established" },
    ],
  },

  // ── DEVI ───────────────────────────────────────────────
  {
    id: "navratri-puja", category: "devi", featured: true,
    name: "Navratri Puja", sanskrit: "नवरात्रि पूजा",
    deity: "Navadurga — Nine forms of Goddess Durga", deityEmoji: "🌸",
    region: "Pan-India", type: "Nine-Night Vrat",
    colors: { bg: "linear-gradient(135deg,#5a0045,#7a005f)", accent: "#8B0045", badge: "#C71585", icon: "#FF69B4" },
    desc: "Nine sacred nights of the Divine Mother across her nine forms — Shailaputri, Brahmacharini, Chandraghanta, Kushmanda, Skandamata, Katyayani, Kalaratri, Mahagauri, and Siddhidatri. The universe itself becomes a puja.",
    when: "Twice a year — Chaitra Navratri (spring, March–April) and Sharad Navratri (autumn, Sept–Oct). Begins on Pratipada (1st) of Shukla Paksha.",
    panchang: [
      { l: "Start", v: "Shukla Pratipada" },
      { l: "Chaitra", v: "March–April" },
      { l: "Sharad", v: "September–October" },
      { l: "Ghatasthapana", v: "First day, Vijaya Muhurta" },
      { l: "Ashtami", v: "Kumari Puja / Kanya Puja" },
      { l: "Vijaya Dashami", v: "10th day — victory" },
    ],
    significance: "The Devi Mahatmya (Durga Saptashati) — 700 verses in the Markandeya Purana — is the scriptural foundation. The Devi's battle against Mahishasura represents the soul's war against ego. Daily akhand jyot (lamp kept burning for nine nights) symbolizes the eternal light of consciousness.",
    samagri: "Kalash with coconut, mango leaves, jau (barley) seeds for sowing, red cloth, red sindoor, red kumkum, red rose and lotus, belpatra, durva, panchamrit, coconut, supari, banana.",
    benefits: [
      { i: "💪", t: "Shakti (Power)", d: "Divine feminine energy awakened within" },
      { i: "🛡️", t: "Protection", d: "The mother's kavach shields all devotees" },
      { i: "💫", t: "Success", d: "Vijaya Dashami brings victory in all fields" },
      { i: "🏥", t: "Healing", d: "Disease and affliction dispelled" },
      { i: "🌺", t: "Beauty & Grace", d: "Goddess Mahagauri bestows radiance" },
      { i: "📚", t: "Wisdom", d: "Saraswati aspect grants knowledge" },
    ],
  },
  {
    id: "lakshmi-puja", category: "devi",
    name: "Lakshmi Puja (Diwali)", sanskrit: "लक्ष्मी पूजा",
    deity: "Goddess Lakshmi", deityEmoji: "🪙",
    region: "Pan-India", type: "Festival & Weekly Puja",
    colors: { bg: "linear-gradient(135deg,#5a4400,#7a5d00)", accent: "#B8860B", badge: "#FFD700", icon: "#FFD700" },
    desc: "The most celebrated puja of the year — the worship of Goddess Lakshmi, the sovereign of wealth, fortune, and auspiciousness. On Diwali night, she walks through illuminated homes, entering where the doors are open and hearts are pure.",
    when: "Diwali (Amavasya of Kartik month) is the prime time. Weekly on Fridays. Also on Purnima, Pradosh, and any Lakshmi-related festival. Stable Lagna and Vrischik (Scorpio) rising recommended.",
    panchang: [
      { l: "Festival", v: "Diwali — Kartik Amavasya" },
      { l: "Weekly", v: "Shukravar (Friday)" },
      { l: "Best Time", v: "Pradosh Kaal (after sunset)" },
      { l: "Lagna", v: "Vrischika Lagna preferred" },
      { l: "2026 Date", v: "October 29, 2026" },
      { l: "Nakshatra", v: "Swati, Vishakha, Purva Bhadra" },
    ],
    significance: "The Lakshmi Stotra from the Rig Veda describes her as born from the churning of the cosmic ocean, seated on a lotus, elephants bathing her. The Sri Sukta (Rig Veda) is the most potent hymn. Chanting \"Om Shreem Mahalakshmiyai Namah\" 108 times activates the abundance vibration.",
    samagri: "Lotus flowers, gold or silver coin, conch shell (shankha), 108 coins, turmeric, kumkum, red cloth, saffron, camphor, ghee deepa, sugarcane, puffed rice (laja), cowrie shells.",
    benefits: [
      { i: "💰", t: "Wealth & Abundance", d: "Financial prosperity in all forms" },
      { i: "🏠", t: "Home Prosperity", d: "Lakshmi enters and stays in pure homes" },
      { i: "🌟", t: "Fame & Prestige", d: "Social status and recognition elevated" },
      { i: "💎", t: "Material Blessings", d: "Tangible gifts of comfort and luxury" },
    ],
  },
  {
    id: "durga-puja", category: "devi",
    name: "Durga Puja", sanskrit: "दुर्गा पूजा",
    deity: "Goddess Durga", deityEmoji: "⚔️",
    region: "West Bengal, Assam, Bihar, Pan-India", type: "Grand Festival Puja",
    colors: { bg: "linear-gradient(135deg,#5a0000,#7a0000)", accent: "#8B0000", badge: "#DC143C", icon: "#FF6347" },
    desc: "The grandest celebration of the Divine Mother — Goddess Durga seated on a lion with ten arms, each wielding a weapon gifted by the gods to defeat Mahishasura. In Bengal, she returns home for five days each year.",
    when: "Saptami to Dashami (7th to 10th day) of Shukla Paksha, Ashwin/Kartik month. Shashthi (6th) sees the Devi's arrival. Navami is the grand Sandhipuja at the junction of Ashtami and Navami.",
    panchang: [
      { l: "Start", v: "Shashthi — Devi arrives" },
      { l: "Saptami", v: "7th — Prana Pratistha" },
      { l: "Ashtami", v: "8th — Sandhi Puja, Kumari" },
      { l: "Navami", v: "9th — Maha Havan" },
      { l: "Dashami", v: "10th — Sindur Khela & immersion" },
      { l: "Month", v: "Ashwin Shukla Paksha" },
    ],
    significance: "The Durga Saptashati (Devi Mahatmya) — 700 shlokas describing three battles — is recited over three days. The Devi's weapon is wisdom; Mahishasura is ego. Dashami (Vijaya Dashami / Dussehra) marks the triumph of divine consciousness over the buffalo-headed delusion.",
    samagri: "Clay idol (in Bengal), red hibiscus (most sacred), bilva leaves, bel patra, 108 lotus flowers, red cloth, 10 types of leaves, sindhur (vermillion for married women).",
    benefits: [
      { i: "💪", t: "Strength & Courage", d: "Fear dissolved, inner warrior awakened" },
      { i: "🛡️", t: "Enemy Protection", d: "All adversaries and obstacles overcome" },
      { i: "🌺", t: "Feminine Power", d: "Women especially blessed and empowered" },
      { i: "✨", t: "Ego Destruction", d: "Mahishasura (ego) slain within" },
    ],
  },
  {
    id: "saraswati-puja", category: "devi",
    name: "Saraswati Puja", sanskrit: "सरस्वती पूजा",
    deity: "Goddess Saraswati", deityEmoji: "🎵",
    region: "Pan-India, especially Bengal, Rajasthan, Schools & Colleges", type: "Festival Puja",
    colors: { bg: "linear-gradient(135deg,#0a3a5e,#104a80)", accent: "#4682B4", badge: "#87CEEB", icon: "#E0E8FF" },
    desc: "On Vasant Panchami, the goddess of knowledge, music, arts, and wisdom manifests in the world. Students place their books, musical instruments, and tools at her feet for blessing. The day heralds the arrival of spring.",
    when: "Panchami (5th) of Shukla Paksha in Magha month (January–February). This is Vasant Panchami — the most auspicious day for beginning any form of learning, initiation, or vidya-arambha.",
    panchang: [
      { l: "Tithi", v: "Shukla Panchami" },
      { l: "Month", v: "Magha" },
      { l: "Festival", v: "Vasant Panchami" },
      { l: "2026 Date", v: "January 24, 2026" },
      { l: "Ideal For", v: "Vidyarambha (starting education)" },
      { l: "Color", v: "Yellow — sacred color of the day" },
    ],
    significance: "The Saraswati Vandana — \"Ya Kundendu Tusharahara Dhavala\" — is the most famous prayer. The Rigveda's Saraswati Sukta (Book 6, Hymn 61) praises her as the great river of inspiration. In Vedic cosmology, Saraswati is the divine voice (Vak) that preceded creation.",
    samagri: "White flowers (preferably), white or yellow garments for deity, ink pot and pen (offered to goddess), musical instruments, books, white sandalwood, yellow sweets, white lotus, kesar (saffron).",
    benefits: [
      { i: "📚", t: "Academic Success", d: "Memory, concentration, and intelligence enhanced" },
      { i: "🎨", t: "Creative Gifts", d: "Arts, music, and creative expression flourish" },
      { i: "💬", t: "Eloquence", d: "Speech and communication refined" },
      { i: "🧠", t: "Wisdom", d: "Discrimination (viveka) and insight deepened" },
    ],
  },
  {
    id: "kali-puja", category: "devi",
    name: "Kali Puja", sanskrit: "काली पूजा",
    deity: "Goddess Kali", deityEmoji: "🗡️",
    region: "West Bengal, Assam, Kerala (as Bhadrakali)", type: "Midnight Puja",
    colors: { bg: "linear-gradient(135deg,#2a0040,#3a005a)", accent: "#4B0082", badge: "#8B008B", icon: "#DA70D6" },
    desc: "The midnight worship of Goddess Kali — the fierce, time-devouring aspect of the Divine Mother. Black as the void before creation, her wild dance upon Shiva represents the dance of consciousness and energy.",
    when: "Amavasya (new moon) of Kartik month — same night as Diwali. Also on Kali Chaudas (14th of Krishna Paksha, Kartik). The entire worship happens from midnight to 3 AM.",
    panchang: [
      { l: "Primary", v: "Kartik Amavasya (Diwali night)" },
      { l: "Also", v: "Kali Chaudas — Kartik Krishna 14" },
      { l: "Puja Time", v: "Midnight to 3 AM (Nishita Kaal)" },
      { l: "2026 Date", v: "October 29, 2026" },
      { l: "Direction", v: "South (Kali's direction)" },
      { l: "Special", v: "Shodashopachar (16 offerings)" },
    ],
    significance: "In Tantric tradition, Kali is the ultimate liberatrix. Her blue-black complexion represents infinite space. Her four hands — sword and severed head in the left, abhaya and vara mudra in the right — signify that she simultaneously destroys and grants fearlessness. Ramakrishna Paramahansa's ecstatic worship of Kali at Dakshineswar is the most celebrated modern example.",
    samagri: "Red hibiscus (most essential), red lotus, red cloth, dark-colored fruits, dark blue or black sesame, panchamrit, camphor, red sandal.",
    benefits: [
      { i: "⚡", t: "Ego Death", d: "The false self dissolved by the mother's sword" },
      { i: "🌑", t: "Shadow Integration", d: "Fear, darkness, and repression transformed" },
      { i: "🧿", t: "Negativity Protection", d: "Kali destroys all dark forces absolutely" },
      { i: "🔥", t: "Liberation", d: "Tantra's direct path to moksha" },
    ],
  },
  {
    id: "varalakshmi", category: "devi",
    name: "Varalakshmi Vratam", sanskrit: "वरलक्ष्मी व्रतम्",
    deity: "Goddess Varalakshmi", deityEmoji: "🌸",
    region: "Andhra Pradesh, Karnataka, Tamil Nadu, Telangana", type: "Women's Vrat",
    colors: { bg: "linear-gradient(135deg,#5a1a4a,#7a2060)", accent: "#8B1A4A", badge: "#FF1493", icon: "#FFB6C1" },
    desc: "Performed by married women on the Friday before Shravana Purnima to invoke the boon-granting form of Lakshmi. A kalash is adorned as the goddess and worshipped with 16 upacharas. The vrat is for the prosperity of the entire family.",
    when: "Shukravar (Friday) preceding Shravana Purnima (full moon in Shravan, July–August). Observed predominantly in South India.",
    panchang: [
      { l: "Day", v: "Friday before Shravana Purnima" },
      { l: "Month", v: "Shravana (July–Aug)" },
      { l: "For", v: "Married women (Sumangalis)" },
      { l: "Fasting", v: "Partial fast until puja is done" },
      { l: "Prasad", v: "Pongal, fruits, coconut" },
      { l: "Vrat Thread", v: "Tied on the wrist after puja" },
    ],
    significance: "Described in the Skanda Purana, this vrat was first performed by Charumati who was granted all boons by Varalakshmi. Tying the holy thread (Varalakshmi doram) on the wrist at the end symbolizes protection of the family.",
    samagri: "Kalash (kalasam), mango leaves, silk saree for kalash, turmeric, kumkum, 9 types of grains, betel leaves, banana, 9 silk threads for vrat thread, flowers (especially lotus), coconut.",
    benefits: [
      { i: "💑", t: "Marital Bliss", d: "Long and happy married life" },
      { i: "👶", t: "Children's Welfare", d: "Blessings for children's health and future" },
      { i: "💰", t: "Household Abundance", d: "Eight forms of Lakshmi invoked" },
      { i: "🌺", t: "Husband's Longevity", d: "Protection and long life for spouse" },
    ],
  },
  {
    id: "hanuman-puja", category: "devi",
    name: "Hanuman Puja", sanskrit: "हनुमान पूजा",
    deity: "Lord Hanuman", deityEmoji: "💪",
    region: "Pan-India, especially North India", type: "Devotional Puja",
    colors: { bg: "linear-gradient(135deg,#5a2a00,#7a3a00)", accent: "#8B4513", badge: "#FF8C00", icon: "#FFD700" },
    desc: "The worship of the greatest devotee — Hanuman, son of the wind god Vayu, whose entire existence is service to Lord Rama. He is invoked for strength, fearlessness, protection from negative forces, and removal of Shani's afflictions.",
    when: "Tuesdays and Saturdays are Hanuman's sacred days. Hanuman Jayanti (Chaitra Purnima) is the grandest puja. Sunrise is the ideal time — the deity prefers the morning energy.",
    panchang: [
      { l: "Sacred Days", v: "Tuesday & Saturday" },
      { l: "Jayanti", v: "Chaitra Purnima (April)" },
      { l: "2026 Date", v: "April 12, 2026" },
      { l: "Ideal Time", v: "Sunrise (Brahma Muhurta)" },
      { l: "Special", v: "During Shani Sade Saati period" },
      { l: "Chalisa", v: "Read 7, 11, or 108 times" },
    ],
    significance: "The Hanuman Chalisa — 40 verses by Goswami Tulsidas — is the most recited prayer in India. \"Jai Hanuman gyan gun sagar.\" Lord Shani himself is said to have promised not to trouble devotees of Hanuman. The Sundarkand of Ramayana describes Hanuman's leaping across the ocean — the supreme act of devotion.",
    samagri: "Sindoor (vermillion) — smeared on entire form of Hanuman, jasmine oil, orange flowers, red garments, betel leaves, banana, coconut, sesame ladoo, tulsi.",
    benefits: [
      { i: "🛡️", t: "Protection from Evil", d: "All negative forces, black magic, enemies repelled" },
      { i: "💪", t: "Strength & Courage", d: "Physical and mental power exponentially increased" },
      { i: "🌙", t: "Shani Relief", d: "Saturn's malefic period greatly softened" },
      { i: "🔥", t: "Fearlessness", d: "All phobias and anxieties dissolved" },
    ],
  },

  // ── GANESHA ────────────────────────────────────────────
  {
    id: "ganesh-chaturthi", category: "ganesh", featured: true,
    name: "Ganesh Chaturthi Puja", sanskrit: "गणेश चतुर्थी पूजा",
    deity: "Lord Ganesha", deityEmoji: "🐘",
    region: "Maharashtra (grandest), Pan-India", type: "Grand Festival Puja",
    colors: { bg: "linear-gradient(135deg,#5a3000,#7a4000)", accent: "#8B4513", badge: "#FF8C00", icon: "#FFD700" },
    desc: "The ten-day grand festival of Lord Ganesha — the remover of obstacles, lord of beginnings, and first deity invoked in any puja. In Mumbai and Pune, million-devotee processions and 20-foot clay idols mark the grandest Hindu festival.",
    when: "Shukla Chaturthi (4th) of Bhadrapada month (August–September). Prana pratistha (life installation) on Chaturthi morning. Visarjan (immersion) on the 11th day (Ananta Chaturdashi).",
    panchang: [
      { l: "Start", v: "Bhadrapada Shukla Chaturthi" },
      { l: "Duration", v: "10 days — 1.5, 5, or 10 day observance" },
      { l: "Prana Pratistha", v: "Morning of Chaturthi" },
      { l: "Visarjan", v: "Ananta Chaturdashi (11th day)" },
      { l: "2026 Date", v: "August 20, 2026" },
      { l: "Avoid", v: "Looking at the moon on Chaturthi" },
    ],
    significance: "The Ganesha Purana and Mudgala Purana are dedicated to Ganesha's glory. He is called Vighneshvara (lord of obstacles) — he both creates and removes obstacles according to cosmic timing. Lokmanya Bal Gangadhar Tilak transformed Ganesh Chaturthi into a pan-national festival in 1893.",
    samagri: "Clay Ganesha idol (eco-friendly), modak (most sacred — 21 modaks), durva grass (21 blades), red flowers (hibiscus), red cloth, red sandalwood paste, 21 paan (betel), coconut, banana.",
    benefits: [
      { i: "🚧", t: "Obstacle Removal", d: "All blocks in life's path cleared" },
      { i: "📖", t: "New Beginnings", d: "Auspicious start to any endeavour" },
      { i: "🧠", t: "Intelligence", d: "Buddhi (intellect) sharpened and refined" },
      { i: "🎯", t: "Success", d: "Siddhi (accomplishment) in all goals" },
      { i: "🛤️", t: "Right Path", d: "Wisdom to choose the righteous road" },
      { i: "💫", t: "Divine Blessings", d: "Ganesha as gateway to all other deities" },
    ],
  },
  {
    id: "sankashti-chaturthi", category: "ganesh",
    name: "Sankashti Chaturthi Vrat", sanskrit: "संकष्टी चतुर्थी व्रत",
    deity: "Lord Ganesha", deityEmoji: "🐘",
    region: "Maharashtra, Gujarat, Karnataka", type: "Monthly Vrat",
    colors: { bg: "linear-gradient(135deg,#4a2a00,#6a3a00)", accent: "#6B4226", badge: "#D2691E", icon: "#FFA500" },
    desc: "Monthly fasting on Krishna Paksha Chaturthi (4th of the waning moon) to invoke Ganesha for the removal of \"sankashta\" — difficulties, sorrows, and impediments. The fast is broken only after moonrise.",
    when: "Krishna Chaturthi (4th of waning moon) every month. The most important is Angarki Chaturthi when this falls on Tuesday — extremely rare and potent.",
    panchang: [
      { l: "Tithi", v: "Krishna Chaturthi (every month)" },
      { l: "Special", v: "Angarki (Tuesday + Chaturthi)" },
      { l: "Fast Break", v: "After moonrise — on sighting the moon" },
      { l: "Most Potent", v: "Bhadrapada Krishna Chaturthi" },
      { l: "Frequency", v: "Monthly" },
      { l: "Story", v: "Sankashti Katha recited at moonrise" },
    ],
    significance: "The Sankashti Vrat Katha (story) is read at moonrise. After seeing the moon and offering it arghya (water and flowers), the fast is broken with Ganesha's prasad. The name \"Sankashti\" literally means \"removal of difficulties\" — and this vrat is specifically for those in trouble.",
    samagri: "Modak, durva grass, red flowers, sesame seeds, coconut, bananas, incense, deepa, red cloth.",
    benefits: [
      { i: "💔", t: "Grief Removal", d: "Sorrows and difficulties dissolve" },
      { i: "🔓", t: "Problem Solving", d: "Stuck situations suddenly resolve" },
      { i: "🌙", t: "Moon's Blessings", d: "Chandra (moon) and Ganesha align" },
      { i: "🌀", t: "Karma Clearing", d: "Accumulated negative karma released" },
    ],
  },

  // ── NAVAGRAHA ──────────────────────────────────────────
  {
    id: "navagraha-puja", category: "navagraha",
    name: "Navagraha Puja", sanskrit: "नवग्रह पूजा",
    deity: "Nine Planetary Deities", deityEmoji: "🪐",
    region: "Pan-India, especially South India", type: "Dosha Nivaran",
    colors: { bg: "linear-gradient(135deg,#1a2a5e,#2a3a80)", accent: "#2C3E7A", badge: "#4169E1", icon: "#87CEEB" },
    desc: "Propitiation of the nine celestial bodies (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, Ketu) that govern different aspects of human destiny. Each planet is a divine intelligence maintaining cosmic order.",
    when: "When a Jyotishi (astrologer) recommends based on horoscope analysis. Also performed at life transitions — marriage, new job, house entry, child's first year. Full moon and new moon days are auspicious.",
    panchang: [
      { l: "Ideal Time", v: "When astrologer prescribes" },
      { l: "For Saturn", v: "Saturday, Shani Jayanti" },
      { l: "For Sun", v: "Sunday, Makar Sankranti" },
      { l: "For Rahu/Ketu", v: "Eclipses, Kalashtami" },
      { l: "General", v: "Nakshatra matching each graha" },
      { l: "Duration", v: "2–4 hours with full vidhi" },
    ],
    significance: "The Graha Mantras in the Rigveda are among the oldest astronomical-spiritual texts. Each planet rules a metal, color, stone, day, grain, and deity. The Navagraha Stotra from the Skanda Purana is the most commonly recited prayer: \"Brahmaa Muraristraipurantakari...\"",
    samagri: "Nine grains (corresponding to each planet), nine metals, nine flowers, nine incense, black sesame for Saturn, red flowers for Sun, white for Moon, nine colored cloths.",
    benefits: [
      { i: "🌟", t: "Dosha Removal", d: "Kal Sarp, Mangal, Shani doshas cleared" },
      { i: "💼", t: "Career Uplift", d: "Professional obstacles dissolved by graha grace" },
      { i: "💍", t: "Marriage", d: "Delays and obstacles to marriage removed" },
      { i: "🏥", t: "Health", d: "Planetary afflictions causing illness healed" },
    ],
  },
  {
    id: "shani-puja", category: "navagraha",
    name: "Shani Puja", sanskrit: "शनि पूजा",
    deity: "Lord Shani (Saturn)", deityEmoji: "🪐",
    region: "Pan-India, especially Shingnapur (Maharashtra)", type: "Graha Puja",
    colors: { bg: "linear-gradient(135deg,#1a1a1a,#2e2e2e)", accent: "#363636", badge: "#696969", icon: "#C0C0C0" },
    desc: "Worship of Lord Shani — the karmic planet who delivers justice with an iron hand. Feared yet revered, Shani teaches through difficulty but rewards with equal generosity. His blessing (Shani Kirpa) transforms poverty into wealth.",
    when: "Every Saturday. Also during Shani Dhaiya (2.5 years), Sade Saati (7.5 years), Shani Jayanti (Amavasya of Jyeshtha), and at Shanishchara temples.",
    panchang: [
      { l: "Day", v: "Shanivar (Saturday)" },
      { l: "Tithi", v: "Amavasya especially potent" },
      { l: "Month", v: "Jyeshtha — Shani Jayanti" },
      { l: "During", v: "Sade Saati or Shani Mahadasha" },
      { l: "Oil", v: "Mustard or sesame oil donation" },
      { l: "Time", v: "Sunset (Pradosh Kaal)" },
    ],
    significance: "Shani is called Danda-Adhipati (lord of punishment) in the Vedic system. But the Shani Stotra calls him \"Soorya Putra\" (son of the Sun) whose severe lessons ultimately lead to enlightenment. The famous Shani Trayodashi (Saturday on the 13th) is extraordinarily auspicious.",
    samagri: "Black sesame (til), mustard oil, urad dal (black lentil), black cloth, black flowers, iron nail, blue sapphire (if prescribed). Donation of oil and iron to the poor is the most effective remedy.",
    benefits: [
      { i: "⚖️", t: "Karmic Balance", d: "Past karma balanced and debts cleared" },
      { i: "🌟", t: "Unexpected Fortune", d: "Shani's grace transforms destiny" },
      { i: "💪", t: "Patience & Discipline", d: "Strength to endure and grow through trials" },
      { i: "🏆", t: "Hard-Won Success", d: "Lasting success built on solid foundations" },
    ],
  },

  // ── LIFECYCLE ──────────────────────────────────────────
  {
    id: "griha-pravesh", category: "lifecycle",
    name: "Griha Pravesh Puja", sanskrit: "गृह प्रवेश पूजा",
    deity: "Vastu Devata, Ganesha, Lakshmi", deityEmoji: "🏠",
    region: "Pan-India", type: "Samskara Puja",
    colors: { bg: "linear-gradient(135deg,#1a4a2a,#22603a)", accent: "#2E8B57", badge: "#32CD32", icon: "#90EE90" },
    desc: "The sacred ritual of entering a new home for the first time. The house is purified, the Vastu Purusha (spirit of the dwelling) is honored, and Lakshmi is invited to reside permanently. First, a cow enters the home — its presence purifies and sanctifies.",
    when: "A Muhurta (auspicious time) must be calculated by an astrologer based on the owner's horoscope, the direction of the house, and the nakshatra. Avoid inauspicious months — Adhik Maas, eclipse months, and the owner's birth month.",
    panchang: [
      { l: "Must Calculate", v: "Muhurta from astrologer" },
      { l: "Best Months", v: "Magha, Phalguna, Vaishakh, Jyeshtha" },
      { l: "Avoid", v: "Adhik Maas, Bhadrapad, Paush" },
      { l: "Best Nakshatra", v: "Rohini, Mrigashira, Anuradha" },
      { l: "First Entry", v: "Boil milk to overflow" },
      { l: "Direction", v: "East-facing door preferred" },
    ],
    significance: "The Vastu Shastra (ancient Indian architectural science) describes the Vastu Purusha as lying with head in the northeast corner. The Griha Pravesh ritual activates the positive Vastu energies and neutralizes negative ones. The cow entering first brings the energy of all 33 crore devatas.",
    samagri: "Kalash, mango leaves, coconut, flowers, raw rice, salt, turmeric, haldi kumkum, new cooking vessels, milk to boil over, camphor, deepa, sweets for neighbors.",
    benefits: [
      { i: "☮️", t: "Peace & Harmony", d: "The home becomes a place of genuine peace" },
      { i: "💰", t: "Prosperity", d: "Lakshmi takes up permanent residence" },
      { i: "🛡️", t: "Protection", d: "Vastu Devata protects against all harm" },
      { i: "👨‍👩‍👧", t: "Family Unity", d: "Bonds between family members strengthened" },
    ],
  },
  {
    id: "vivah-puja", category: "lifecycle",
    name: "Vivah Puja (Wedding Rituals)", sanskrit: "विवाह पूजा",
    deity: "Brahma, Agni, Indra, the Seven Sages", deityEmoji: "💒",
    region: "Pan-India", type: "Samskara",
    colors: { bg: "linear-gradient(135deg,#5a1a08,#7a2812)", accent: "#8B2500", badge: "#FF4500", icon: "#FFA07A" },
    desc: "The most sacred of the 16 samskaras — Hindu marriage is a cosmic covenant witnessed by fire (Agni), the seven stars (Saptarishi), and the eternal vow of Saptapadi (seven steps). The couple becomes one in the eyes of the universe.",
    when: "Only during auspicious Vivah Muhurats determined by the horoscopes of both partners. Uttara Phalguni, Uttara Ashadha, Uttara Bhadra, Rohini, Mrigashira are the best nakshatras. Avoid Adhik Maas and eclipses.",
    panchang: [
      { l: "Muhurta", v: "Calculated from both horoscopes" },
      { l: "Best Nakshatra", v: "Uttara Phalguni, Rohini, Mrigashira" },
      { l: "Best Lagnas", v: "Taurus, Gemini, Cancer" },
      { l: "Avoid", v: "Adhik Maas, Bhadrapada, eclipses" },
      { l: "Auspicious", v: "Jupiter direct and strong" },
      { l: "Duration", v: "24+ hours of rituals traditionally" },
    ],
    significance: "The Atharvaveda's marriage hymns (Book 14) are the oldest wedding prayers in the world. Saptapadi (seven steps) is the legal and spiritual heart of the ceremony — once completed, the marriage is irrevocable. Each step corresponds to a vow — food, strength, wealth, happiness, children, cattle, and devotion.",
    samagri: "Sacred fire (Agni kund), ghee, seven types of grain, wedding garments, mangalsutra, sindoor (vermillion), flower garland (varmala), coconut, areca nuts, banana, 7 paan leaves.",
    benefits: [
      { i: "💑", t: "Sacred Union", d: "Two souls bound across seven lifetimes" },
      { i: "🌺", t: "Dharmic Life", d: "Foundation of Grihasta ashrama" },
      { i: "👶", t: "Progeny", d: "Blessings for healthy, wise children" },
      { i: "🌟", t: "Social Harmony", d: "Family, community, and cosmic order aligned" },
    ],
  },
  {
    id: "upanayana", category: "lifecycle",
    name: "Upanayana (Thread Ceremony)", sanskrit: "उपनयन संस्कार",
    deity: "Brahma, Gayatri Devi, Guru", deityEmoji: "🧵",
    region: "North & South India", type: "Samskara",
    colors: { bg: "linear-gradient(135deg,#4a4a0a,#5e5e10)", accent: "#808000", badge: "#9ACD32", icon: "#F5DEB3" },
    desc: "The sacred thread ceremony (Yajnopavita) — the second birth that initiates a young boy (8–12 years) into Vedic learning. He receives the sacred thread and the Gayatri Mantra for the first time from his Guru. Brahmacharya begins.",
    when: "Calculated muhurta. Typically in Uttarayana (sun's northward journey, Jan–June). Shubha nakshatras — Hasta, Ashwini, Pushya, Uttara Phalguni are ideal. Often performed just before higher education begins.",
    panchang: [
      { l: "Age", v: "8 (Brahmin), 11 (Kshatriya), 12 (Vaishya)" },
      { l: "Best Period", v: "Uttarayana (Jan–June)" },
      { l: "Nakshatra", v: "Hasta, Ashwini, Pushya, U. Phalguni" },
      { l: "Avoid", v: "Krishna Paksha, boy's birth month" },
      { l: "Muhurta", v: "Morning — Brahma Muhurta ideal" },
      { l: "Duration", v: "Full-day ceremony" },
    ],
    significance: "The Gayatri Mantra — received whispered in the right ear by the Guru — is the most powerful mantra in the Vedas. \"Tat Savitur Varenyam Bhargo Devasya Dhimahi Dhiyo Yo Nah Prachodayat.\" The Manusmriti calls Upanayana the \"dvijatva\" — the second birth, the birth of the intellectual-spiritual self.",
    samagri: "Sacred thread (Yajnopavita — cotton, three strands), deer skin cloth, bamboo staff, yellow garment, sacred fire, ghee, sesame, samidha (sacred wood for havan), munja grass for girdle.",
    benefits: [
      { i: "📖", t: "Vedic Education", d: "Gateway to the knowledge of all Vedas" },
      { i: "🧘", t: "Discipline", d: "Brahmacharya — self-mastery from youth" },
      { i: "🌟", t: "Sacred Lineage", d: "Connection to the Guru-Shishya parampara" },
      { i: "🧠", t: "Intellect", d: "Gayatri Mantra activates divine intelligence" },
    ],
  },

  // ── REGIONAL ───────────────────────────────────────────
  {
    id: "onam-puja", category: "regional",
    name: "Onam Puja (Thrikkakara)", sanskrit: "ओणम पूजा",
    deity: "King Mahabali, Lord Vamana", deityEmoji: "🌺",
    region: "Kerala", type: "Harvest Festival Puja",
    colors: { bg: "linear-gradient(135deg,#0a4a0a,#0f5e0f)", accent: "#006400", badge: "#228B22", icon: "#90EE90" },
    desc: "Kerala's grandest festival — marking the annual return of the benevolent demon king Mahabali to his kingdom. The Pookkalam (flower carpet) is created for ten days and Onasadhya (grand feast of 26+ dishes on banana leaf) is the sacred offering.",
    when: "Thiruvonam Nakshatra in the Malayalam month of Chingam (August–September). The ten-day celebration begins on Atham Nakshatra and culminates on Thiruvonam — the grandest day.",
    panchang: [
      { l: "Month", v: "Chingam (August–September)" },
      { l: "Key Day", v: "Thiruvonam Nakshatra" },
      { l: "Duration", v: "10 days (Atham to Thiruvonam)" },
      { l: "Pookkalam", v: "Created fresh each of 10 days" },
      { l: "Sadya", v: "26-dish feast on banana leaf" },
      { l: "For", v: "Harvest & community" },
    ],
    significance: "The story: Mahabali was such a righteous king that the gods were threatened. Vishnu appeared as Vamana (dwarf) and asked for three paces of land — then grew to cosmic size, covering all creation in two steps. The third step placed on Mahabali's head sent him to the netherworld, with the boon to return once a year to see his people.",
    samagri: "Fresh flowers (especially marigold, rose, chrysanthemum) for Pookkalam, banana leaves for feast, 26+ vegetable dishes for Onasadhya, Thrikkakara appan (clay idol of Vamana), incense, lamps.",
    benefits: [
      { i: "🌾", t: "Harvest Abundance", d: "Kerala's rice harvest blessed" },
      { i: "🤝", t: "Community Unity", d: "All communities celebrate together" },
      { i: "🎊", t: "Joy & Festivity", d: "Pure happiness as the golden age returns" },
      { i: "🏘️", t: "Cultural Pride", d: "The best of Kerala's civilization honored" },
    ],
  },
  {
    id: "bihu-puja", category: "regional",
    name: "Bihu Puja", sanskrit: "बिहु पूजा",
    deity: "Brahma, Earth Goddess (Vasundhara), Cattle", deityEmoji: "🐄",
    region: "Assam", type: "Agricultural Festival Puja",
    colors: { bg: "linear-gradient(135deg,#0f4a0f,#155e15)", accent: "#2E8B57", badge: "#3CB371", icon: "#7CFC00" },
    desc: "Assam's triple harvest festival — Rongali Bihu (spring/new year), Kangali Bihu (autumn), and Bhogali Bihu (winter harvest). At the heart is a veneration of the earth, cattle, and the cycle of agricultural abundance.",
    when: "Rongali Bihu: mid-April (Bohag Bihu, New Year). Bohag 1 on the Assamese calendar — corresponds to Baisakhi in North India. Seven-day celebration.",
    panchang: [
      { l: "Rongali Bihu", v: "Mid-April (New Year)" },
      { l: "Kangali Bihu", v: "Mid-October (kati month)" },
      { l: "Bhogali Bihu", v: "Mid-January (harvest feast)" },
      { l: "Key Ritual", v: "Husori (prayer songs at dawn)" },
      { l: "Cattle Puja", v: "On Goru Bihu (first day)" },
      { l: "Fire", v: "Meji bonfire on Bhogali night" },
    ],
    significance: "Bihu is inseparable from the Brahmaputra valley's agricultural identity. The cattle (particularly oxen) are bathed, fed with gourd and melon, and given a special paste of black sesame and mustard. The ancestral spirits are propitiated. Bihu dance — a joyous expression of nature worship — is performed in fields.",
    samagri: "Gourd, melon, mustard paste for cattle bath, pithas (rice cakes), mustard oil, turmeric, rice, banana, fruits.",
    benefits: [
      { i: "🌱", t: "Agricultural Prosperity", d: "Abundant harvest prayed for" },
      { i: "🐄", t: "Cattle Welfare", d: "Livestock health and productivity ensured" },
      { i: "🎉", t: "New Year's Joy", d: "Fresh start aligned with natural cycles" },
      { i: "🌿", t: "Earth Gratitude", d: "Vasundhara (earth goddess) honored" },
    ],
  },
  {
    id: "tirupati-seva", category: "regional",
    name: "Tirupati Balaji Archana", sanskrit: "तिरुपति वेंकटेश्वर अर्चना",
    deity: "Lord Venkateswara (Balaji)", deityEmoji: "🛕",
    region: "Andhra Pradesh, Telangana", type: "Temple Archana",
    colors: { bg: "linear-gradient(135deg,#5a4400,#7a5e00)", accent: "#8B6914", badge: "#FFD700", icon: "#FAFAD2" },
    desc: "Venkateswara is Lord Vishnu who took a mortal loan from Kubera to marry Padmavathi. Until that loan is repaid by devotees' offerings, he remains on earth. The richest temple in the world receives 100,000 pilgrims daily.",
    when: "Daily darshan — but Ekadashi (11th tithi) and Saturdays are most auspicious. Special festivals: Brahmotsavam (9-day annual festival), Vaikunta Ekadashi (December–January) when the Vaikunta Dwaram opens.",
    panchang: [
      { l: "Best Day", v: "Ekadashi, Saturday" },
      { l: "Special", v: "Brahmotsavam (9 days, Sep)" },
      { l: "Sacred", v: "Vaikunta Ekadashi (Dec/Jan)" },
      { l: "Temple", v: "Tirumala, Andhra Pradesh" },
      { l: "Offerings", v: "Hair donation, Laddu prasadam" },
      { l: "Archana", v: "With 108 names of Venkateswara" },
    ],
    significance: "The Tiruvenkatam (hill of Venkata) is described in the Vayu Purana and Skanda Purana. Venkateswara is the Kaliyuga form of Vishnu — especially accessible and merciful in this age of darkness. The famous Laddu prasadam is made by 700 cooks daily from the donations of 10 million+ yearly pilgrims.",
    samagri: "Silk garments (most common donation), coconut, camphor, tilaka for deity. Hair donation (Keshavarpana) is the most powerful personal offering. TTD controls all offerings and worship protocols.",
    benefits: [
      { i: "🙏", t: "All Desires Fulfilled", d: "Venkateswara grants any boon sought sincerely" },
      { i: "💰", t: "Debt Freedom", d: "Financial burdens lifted — karma of debt cleared" },
      { i: "📚", t: "Education", d: "Children's learning and career blessed" },
      { i: "🌸", t: "Liberation", d: "The darshan of Venkateswara grants moksha" },
    ],
  },
  {
    id: "jagannath-puja", category: "regional",
    name: "Jagannath Rath Yatra Puja", sanskrit: "जगन्नाथ रथयात्रा पूजा",
    deity: "Lord Jagannath (Vishnu-Krishna)", deityEmoji: "🛕",
    region: "Odisha (Puri), Replicated globally", type: "Grand Procession Puja",
    colors: { bg: "linear-gradient(135deg,#5a0000,#7a0000)", accent: "#8B0000", badge: "#FF4500", icon: "#FFD700" },
    desc: "The world's largest chariot procession — three massive wooden chariots of Jagannath, Balabhadra, and Subhadra are pulled through Puri's Grand Road by a million devotees. Chaitanya Mahaprabhu wept with ecstasy before this deity.",
    when: "Shukla Dwitiya (2nd) of Ashadha month (June–July). The nine-day Yatra culminates with Bahuda Yatra (return journey). Snana Yatra (bathing festival) on Jyeshtha Purnima precedes the Yatra.",
    panchang: [
      { l: "Yatra Start", v: "Ashadha Shukla Dwitiya" },
      { l: "Duration", v: "9 days" },
      { l: "Snana Yatra", v: "Jyeshtha Purnima (108 pots)" },
      { l: "2026 Date", v: "June 27, 2026" },
      { l: "Return", v: "Bahuda Yatra — Ashadha Shukla 10" },
      { l: "Scale", v: "10 lakh+ devotees in Puri" },
    ],
    significance: "Jagannath — \"Lord of the Universe\" — is unique in Hinduism: his form is abstract, unfinished, with large circular eyes. Tradition says the sculptor (Vishvakarma) was told not to be interrupted — when the king broke the rule, the carving stopped, leaving Jagannath in his current form. The Atharva Veda's cosmological hymns are its scriptural basis.",
    samagri: "Chandan (sandalwood) paste, tulsi, basil, camphor, flowers. At Puri temple: special Chhappan Bhog (56 food items as prasadam — Mahaprasad, the greatest offering in the Vaishnava tradition).",
    benefits: [
      { i: "👁️", t: "Divine Vision", d: "A single glimpse grants lifetime of merit" },
      { i: "🍚", t: "Mahaprasad Grace", d: "Jagannath's prasad removes all sins" },
      { i: "🌍", t: "Universal Love", d: "Jagannath belongs to all — no caste barriers" },
      { i: "🎠", t: "Bhakti Awakening", d: "Pure devotion ignited in the heart" },
    ],
  },
  {
    id: "chhath-puja", category: "regional",
    name: "Chhath Puja", sanskrit: "छठ पूजा",
    deity: "Surya (Sun God) & Chhathi Maiya", deityEmoji: "☀️",
    region: "Bihar, UP, Jharkhand, globally by diaspora", type: "Solar Worship",
    colors: { bg: "linear-gradient(135deg,#5a2a00,#7a3a00)", accent: "#B8501A", badge: "#FF8C00", icon: "#FFD700" },
    desc: "The most rigorous and ecologically pure festival in India — a 36-hour waterless fast by women who stand waist-deep in river water to offer arghya (sacred water offering) to the rising and setting sun.",
    when: "Kartik Shukla Shashthi (6th of waxing moon in Kartik month, October–November). Four-day festival: Nahay Khay, Kharna, Sandhya Arghya (sunset), and Usha Arghya (sunrise).",
    panchang: [
      { l: "Primary", v: "Kartik Shukla Shashthi" },
      { l: "Nahay Khay", v: "Chaturthi — purification bath" },
      { l: "Kharna", v: "Panchami — Kheer offered to Surya" },
      { l: "Sunset Arghya", v: "Shashthi evening — at riverbank" },
      { l: "Sunrise Arghya", v: "Saptami morning — breaking fast" },
      { l: "2026 Date", v: "October 21–24, 2026" },
    ],
    significance: "The Chhath Mahaparva (Rig Veda Book 1, Hymn 50 — Surya Sukta) is the oldest solar worship tradition. The Vedic verse \"Udayan tvaditya\" is sung at sunrise. Standing in water while offering to the sun is a direct contact with the five elements. No priest is needed — it is a self-performing puja of the highest power.",
    samagri: "Bamboo baskets (daura), sugarcane stalks, seasonal fruits, thekua (sweet), rice pancake (Kasar), coconut, banana, fresh turmeric, ginger, paan, supari, earthen lamps. All offerings handmade by the worshipper.",
    benefits: [
      { i: "☀️", t: "Solar Vitality", d: "Surya's life force energy absorbed directly" },
      { i: "💚", t: "Health Restoration", d: "The most powerful healing ritual in India" },
      { i: "👶", t: "Children's Well-being", d: "Sons especially blessed by Chhathi Maiya" },
      { i: "🌊", t: "Purification", d: "36-hour fast purifies body, mind, and karma" },
    ],
  },
];
